---
sidebar: sidebar 
permalink: concept-install-options-azure.html 
keywords: install connector azure, azure install connector, connector azure, azure connector, installation options, azure marketplace, manual install 
summary: Existem algumas maneiras diferentes de criar um agente de console no Azure.  Diretamente do NetApp Console é a maneira mais comum. 
---
= Opções de instalação do agente de console no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Existem algumas maneiras diferentes de criar um agente de console no Azure.  Diretamente do NetApp Console é a maneira mais comum.

As seguintes opções de instalação estão disponíveis:

* link:task-install-agent-azure-console.html["Crie um agente de console diretamente do NetApp Console"](esta é a opção padrão)
+
Esta ação inicia uma VM executando Linux e o software do agente do Console em uma VNet de sua escolha.

* link:task-install-agent-azure-marketplace.html["Crie um agente de console no Azure Marketplace"]
+
Esta ação também inicia uma VM executando Linux e o software do agente do Console, mas a implantação é iniciada diretamente do Azure Marketplace, e não do Console.

* link:task-install-agent-azure-manual.html["Baixe e instale manualmente o software em seu próprio host Linux"]


A opção de instalação escolhida afeta a maneira como você se prepara para a instalação.  Isso inclui como você fornece ao agente do Console as permissões necessárias para autenticar e gerenciar recursos no Azure.
