---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: Você usa um agente do Console para conectar o NetApp Console à sua infraestrutura e orquestrar com segurança soluções de armazenamento em ambientes AWS, Azure, Google Cloud ou locais, além de usar serviços de proteção de dados. 
---
= Saiba mais sobre os agentes do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você usa um agente do Console para conectar o NetApp Console à sua infraestrutura e orquestrar com segurança soluções de armazenamento em ambientes AWS, Azure, Google Cloud ou locais, além de usar serviços de proteção de dados.

Um agente de console permite que você:

* Orquestre tarefas de gerenciamento de armazenamento a partir do NetApp Console , como provisionamento do Cloud Volumes ONTAP, configuração de volumes de armazenamento, uso de classificação de dados e muito mais.
* Autentique-se usando as funções IAM do seu provedor de nuvem para integração de faturamento de assinaturas.
* Utilize serviços de dados avançados (NetApp Backup and Recovery, NetApp Disaster Recovery, NetApp Ransomware Resilience e NetApp Cloud Tiering).
* Utilize o console no modo restrito.


Se você não precisa de orquestração avançada ou proteção de dados, pode gerenciar centralmente clusters ONTAP locais e serviços de armazenamento nativos da nuvem sem implantar um agente. Ferramentas de monitoramento e mobilidade de dados também estão disponíveis.

A tabela a seguir mostra quais recursos e serviços você pode usar com e sem um agente do Console.

[cols="40,20a,20a"]
|===
|  | Disponível com agente | Disponível sem agente 


3+| *Sistemas de armazenamento suportados*: 


| Amazon FSx para ONTAP  a| 
Sim (recursos de descoberta e gerenciamento)
 a| 
Sim (somente descoberta)



| Armazenamento Amazon S3  a| 
Sim
 a| 
Não



| Armazenamento de Blobs do Azure  a| 
Sim
 a| 
Sim



| Azure NetApp Files  a| 
Sim
 a| 
Sim



| Cloud Volumes ONTAP  a| 
Sim
 a| 
Não



| Sistemas da série E  a| 
Sim
 a| 
Não



| Google Cloud NetApp Volumes  a| 
Sim
 a| 
Sim



| Buckets de armazenamento do Google Cloud  a| 
Sim
 a| 
Não



| Sistemas StorageGRID  a| 
Sim
 a| 
Não



| Cluster ONTAP local (gerenciamento e descoberta avançados)  a| 
Sim (gestão e descoberta avançadas)
 a| 
Não (apenas descoberta básica)



3+| *Serviços de gestão de armazenamento disponíveis*: 


| Alertas  a| 
Sim
 a| 
Não



| Centro de automação  a| 
Sim
 a| 
Sim



| Digital Advisor (Active IQ)  a| 
Sim
 a| 
Não



| Gerenciamento de licenças e assinaturas  a| 
Sim
 a| 
Não



| Eficiência econômica  a| 
Sim
 a| 
Não



| Métricas do painel da página inicial  a| 
Sim^2^
 a| 
Não



| Planejamento do ciclo de vida  a| 
Sim
 a| 
Não^1^



| Sustentabilidade  a| 
Sim
 a| 
Não



| Atualizações de software  a| 
Sim
 a| 
Sim



| Cargas de trabalho da NetApp  a| 
Sim
 a| 
Sim



3+| *Serviços de dados disponíveis*: 


| NetApp Backup and Recovery  a| 
Sim
 a| 
Não



| Classificação de Dados  a| 
Sim
 a| 
Não



| NetApp Cloud Tiering  a| 
Sim
 a| 
Não



| NetApp Copy and Sync  a| 
Sim
 a| 
Não



| NetApp Disaster Recovery  a| 
Sim
 a| 
Não



| NetApp Ransomware Resilience  a| 
Sim
 a| 
Não



| NetApp Volume Caching  a| 
Sim
 a| 
Não

|===
^1^ É possível visualizar o planejamento do ciclo de vida sem um agente do console, mas um agente do console é necessário para iniciar ações.

^2^ Métricas precisas na página inicial exigem agentes de console com tamanho e configuração adequados.



== Os agentes do console devem estar operacionais o tempo todo

Os agentes de console são uma parte fundamental do NetApp Console.  É sua responsabilidade (o cliente) garantir que os agentes relevantes estejam sempre ativos, operacionais e acessíveis.  O Console pode lidar com pequenas interrupções do agente, mas você deve corrigir falhas de infraestrutura rapidamente.

Esta documentação é regida pelo CLUF.  Operar o produto fora da documentação pode afetar sua funcionalidade e seus direitos de EULA.



== Locais suportados

Você pode instalar agentes nos seguintes locais:

* Serviços Web da Amazon
* Microsoft Azure
+
Implante um agente de console no Azure na mesma região que os sistemas Cloud Volumes ONTAP que ele gerencia.  Alternativamente, implante-o no https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Par de regiões do Azure"^] .  Isso garante que uma conexão do Azure Private Link seja usada entre o Cloud Volumes ONTAP e suas contas de armazenamento associadas. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Saiba como o Cloud Volumes ONTAP usa um Azure Private Link"^]

* Google Cloud
+
Para usar o Console e os serviços de dados com o Google Cloud, implante seu agente no Google Cloud.

* Nas suas instalações




== Comunicação com provedores de nuvem

O agente usa TLS 1.3 para todas as comunicações com AWS, Azure e Google Cloud.



== Modo restrito

Para usar o Console no modo restrito, instale um agente do Console e acesse a interface do Console que está sendo executada localmente no agente do Console.

link:concept-modes.html["Saiba mais sobre os modos de implantação do NetApp Console"] .



== Como instalar um agente de console

Você pode instalar um agente do Console diretamente do Console, do marketplace do seu provedor de nuvem ou instalando manualmente o software no seu próprio host Linux ou no seu ambiente VCenter.

* link:concept-modes.html["Saiba mais sobre os modos de implantação do NetApp Console"]
* link:task-quick-start-standard-mode.html["Comece a usar o NetApp Console no modo padrão"]
* link:task-quick-start-restricted-mode.html["Comece a usar o NetApp Console no modo restrito"]




== Permissões do provedor de nuvem

Você precisa de permissões específicas para criar o agente do Console diretamente do NetApp Console e outro conjunto de permissões para o próprio agente do Console. Se você criar o agente do Console na AWS ou no Azure diretamente do Console, o Console criará o agente do Console com as permissões necessárias.

Ao usar o Console no modo padrão, a maneira como você fornece permissões depende de como você planeja criar o agente do Console.

Para saber como configurar permissões, consulte o seguinte:

* Modo padrão
+
** link:concept-install-options-aws.html["Opções de instalação do agente na AWS"]
** link:concept-install-options-azure.html["Opções de instalação do agente no Azure"]
** link:concept-install-options-google.html["Opções de instalação do agente no Google Cloud"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["Configurar permissões de nuvem para implantações locais"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configurar permissões para o modo restrito"]


Para visualizar as permissões exatas que o agente do Console precisa para operações diárias, consulte as seguintes páginas:

* link:reference-permissions-aws.html["Aprenda como o agente do Console usa as permissões da AWS"]
* link:reference-permissions-azure.html["Aprenda como o agente do Console usa as permissões do Azure"]
* link:reference-permissions-gcp.html["Saiba como o agente do Console usa as permissões do Google Cloud"]


É sua responsabilidade atualizar as políticas do agente do Console à medida que novas permissões são adicionadas em versões subsequentes.  As notas de versão listam novas permissões.



== Atualizações de agentes

A NetApp atualiza o software do agente mensalmente para adicionar recursos e melhorar a estabilidade.  Alguns recursos do Console, como o Cloud Volumes ONTAP e o gerenciamento de cluster ONTAP local, dependem da versão e das configurações do agente do Console.

Ao instalar o agente na nuvem, o agente do Console é atualizado automaticamente, desde que tenha acesso à internet.



== Manutenção de sistema operacional e VM

Manter o sistema operacional no host do agente do Console é responsabilidade sua (do cliente).  Por exemplo, você (cliente) deve aplicar atualizações de segurança ao sistema operacional no host do agente do Console seguindo os procedimentos padrão da sua empresa para distribuição do sistema operacional.

Observe que você (cliente) não precisa interromper nenhum serviço no host do Console Gent ao aplicar pequenas atualizações de segurança.

Se você (cliente) precisar parar e iniciar a VM do agente do Console, faça isso no console do seu provedor de nuvem ou usando os procedimentos padrão para gerenciamento local.

<<agents-must-be-operational-at-all-times,O agente do Console deve estar operacional o tempo todo>> .



== Vários sistemas e agentes

Um agente pode gerenciar vários sistemas e dar suporte a serviços de dados no Console.  Você pode usar um único agente para gerenciar vários sistemas com base no tamanho da implantação e nos serviços de dados que você usa.

Para implantações em larga escala, trabalhe com seu representante da NetApp para dimensionar seu ambiente.  Entre em contato com o Suporte da NetApp se tiver problemas.

Aqui estão alguns exemplos de implantações de agentes:

* Você tem um ambiente multicloud (por exemplo, AWS e Azure) e prefere ter um agente na AWS e outro no Azure.  Cada um gerencia os sistemas Cloud Volumes ONTAP em execução nesses ambientes.
* Um provedor de serviços pode usar uma organização do Console para fornecer serviços aos seus clientes, enquanto usa outra organização para fornecer recuperação de desastres para uma de suas unidades de negócios.  Cada organização precisa de seu próprio agente.

