---
sidebar: sidebar 
permalink: concept-install-options-google.html 
keywords: install connector google cloud, google cloud install connector, connector google cloud, google cloud connector, install connector gcp, gcp install connector, connector gcp, gcp connector, installation options, manual install 
summary: Existem algumas maneiras diferentes de criar um agente do Console no Google Cloud.  Diretamente do NetApp Console é a maneira mais comum. 
---
= Opções de instalação do agente de console no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Existem algumas maneiras diferentes de criar um agente do Console no Google Cloud.  Diretamente do NetApp Console é a maneira mais comum.  ---

As seguintes opções de instalação estão disponíveis:

* link:task-install-agent-google-console-gcloud.html["Crie o agente do Console diretamente do Console"](esta é a opção padrão)
+
Esta ação inicia uma instância de VM executando Linux e o software do agente do Console em uma VPC de sua escolha.

* link:task-install-agent-google-console-gcloud.html["Crie o agente do Console usando a plataforma Google"]
+
Esta ação também inicia uma instância de VM executando o Linux e o software do agente do Console, mas a implantação é iniciada diretamente do Google Cloud, e não do Console.

* link:task-install-agent-google-manual.html["Baixe e instale manualmente o software em seu próprio host Linux"]


A opção de instalação escolhida afeta a maneira como você se prepara para a instalação.  Isso inclui como você fornece ao Console as permissões necessárias para autenticar e gerenciar recursos no Google Cloud.
