---
settings:
  name: NetApp Console setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Configuração e administração do NetApp Console
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Limitações conhecidas
      url: "/reference-limitations.html"
    - title: Alterações nos sistemas operacionais Linux suportados
      url: "/reference-agent-operating-system-changes.html"
  - title: Começar
    entries:
    - title: Aprenda o básico
      entries:
      - title: NetApp Console
        url: "/concept-overview.html"
      - title: Agentes de console
        url: "/concept-agents.html"
      - title: Modos de implantação
        url: "/concept-modes.html"
    - title: Comece a usar o assistente do NetApp Console
      entries:
      - title: Use o assistente do NetApp Console
        url: "/task-console-assistant.html"
    - title: Comece com o modo padrão
      entries:
      - title: Fluxo de trabalho de introdução
        url: "/task-quick-start-standard-mode.html"
      - title: Preparar o acesso à rede para o NetApp Console
        url: "/reference-networking-saas-console.html"
      - title: Inscreva-se no NetApp Console
        url: "/task-sign-up-saas.html"
      - title: Criar um agente de console
        entries:
        - title: AWS
          entries:
          - title: Opções de instalação do agente de console
            url: "/concept-install-options-aws.html"
          - title: Criar um agente de console a partir do NetApp Console
            url: "/task-install-agent-aws-console.html"
          - title: Crie um agente de console no marketplace
            url: "/task-install-agent-aws-marketplace.html"
          - title: Instalar manualmente o agente do Console
            url: "/task-install-agent-aws-manual.html"
        - title: Azul
          entries:
          - title: Opções de instalação do agente de console
            url: "/concept-install-options-azure.html"
          - title: Criar um agente de console a partir do NetApp Console
            url: "/task-install-agent-azure-console.html"
          - title: Crie um agente de console no marketplace
            url: "/task-install-agent-azure-marketplace.html"
          - title: Instalar manualmente o agente do Console
            url: "/task-install-agent-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Opções de instalação do agente de console
            url: "/concept-install-options-google.html"
          - title: Criar um agente de console a partir do NetApp Console
            url: "/task-install-agent-google-console-gcloud.html"
          - title: Crie um agente de console do Google Cloud
            url: "/task-install-agent-google-gcloud.html"
          - title: Instalar manualmente o agente do Console
            url: "/task-install-agent-google-manual.html"
        - title: Instalar um agente no local
          entries:
          - title: Instalar manualmente um agente no local
            url: "/task-install-agent-on-prem.html"
          - title: Instalar um agente local no VCenter
            url: "/task-install-agent-on-prem-ova.html"
      - title: Assine os NetApp Intelligent Services
        url: "/task-subscribe-standard-mode.html"
      - title: O que você pode fazer a seguir
        url: "/reference-whats-next.html"
    - title: Comece com o modo restrito
      entries:
      - title: Fluxo de trabalho de introdução
        url: "/task-quick-start-restricted-mode.html"
      - title: Preparar para implantação
        url: "/task-prepare-restricted-mode.html"
      - title: Implantar o agente do Console
        url: "/task-install-restricted-mode.html"
      - title: Assine os NetApp Intelligent Services
        url: "/task-subscribe-restricted-mode.html"
      - title: O que você pode fazer a seguir
        url: "/reference-whats-next-restricted-mode.html"
    - title: Comece com a interface legada do BlueXP (modo privado)
      entries:
      - title: Introdução à interface legada do BlueXP (modo privado)
        url: "/task-quick-start-private-mode.html"
  - title: Usar o NetApp Console
    entries:
    - title: Efetue login no NetApp Console
      url: "/task-logging-in.html"
    - title: Exibir métricas na página inicial do NetApp Console
      url: "/task-dashboard.html"
    - title: Gerencie as configurações de usuário do NetApp Console
      url: "/task-user-settings.html"
  - title: Administrar o NetApp Console
    entries:
    - title: Gerenciamento de identidade e acesso
      entries:
      - title: Saiba mais sobre como gerenciar identidade e acesso
        url: "/concept-identity-and-access-management.html"
      - title: Comece com identidade e acesso
        url: "/task-iam-get-started.html"
      - title: Organize seus recursos com pastas e projetos
        url: "/task-iam-manage-folders-projects.html"
      - title: Gerenciar membros e contas de serviço
        url: "/task-iam-manage-members-permissions.html"
      - title: Use funções para controlar o acesso dos membros aos recursos
        url: "/task-iam-manage-roles.html"
      - title: Gerencie sua hierarquia de recursos
        url: "/task-iam-manage-resources.html"
      - title: Associar um agente do Console a outras pastas e projetos
        url: "/task-iam-associate-agents.html"
      - title: Alternar entre organizações, projetos e agentes do Console
        url: "/task-iam-switch-organizations-projects.html"
      - title: IDs de organização e projeto
        url: "/task-iam-rename-organization.html"
      - title: Monitorar ou auditar a atividade do IAM
        url: "/task-iam-audit-actions-timeline.html"
      - title: Funções de acesso ao NetApp Console
        entries:
        - title: Saiba mais sobre as funções de acesso do NetApp Console
          url: "/reference-iam-predefined-roles.html"
        - title: Funções da plataforma
          url: "/reference-iam-platform-roles.html"
        - title: Funções de aplicação
          entries:
          - title: Funções do Google Cloud NetApp Volumes
            url: "/reference-iam-gcnv-roles.html"
          - title: Papéis- Keystone
            url: "/reference-iam-keystone-roles.html"
          - title: Analista de suporte de operações
            url: "/reference-iam-analyst-roles.html"
          - title: Funções de armazenamento
            url: "/reference-iam-storage-roles.html"
        - title: Funções de serviços de dados
          entries:
          - title: Funções de backup e recuperação
            url: "/reference-iam-backup-rec-roles.html"
          - title: Funções de recuperação de desastres
            url: "/reference-iam-disaster-rec-roles.html"
          - title: Funções de proteção contra ransomware
            url: "/reference-iam-ransomware-roles.html"
    - title: Organizações parceiras
      entries:
      - title: Saiba mais sobre parcerias organizacionais
        url: "/concept-org-partnerships.html"
      - title: Crie uma parceria organizacional
        url: "/task-partnerships-create.html"
      - title: Gerenciar membros de uma organização parceira
        url: "/task-partnerships-assign-users.html"
      - title: Gerenciar acesso a recursos para uma organização parceira
        url: "/task-partnerships-resource-access.html"
      - title: Trabalhar em uma organização parceira
        url: "/task-partnerships-work.html"
    - title: Federação de identidade
      entries:
      - title: Saiba mais sobre federação de identidade
        url: "/concept-federation.html"
      - title: Verificação de domínio
        entries:
        - title: Verifique seu domínio
          url: "/task-federation-verify-domain.html"
      - title: Configurar federações
        entries:
        - title: Federar com um provedor de Serviços de Federação do Active Directory
            (AD FS)
          url: "/task-federation-adfs.html"
        - title: Federar com o provedor Microsoft Entra ID
          url: "/task-federation-entra-id.html"
        - title: Federar com PingFederate
          url: "/task-federation-ping.html"
        - title: Federe com um provedor de identidade SAML
          url: "/task-federation-saml.html"
      - title: Gerenciar federações
        url: "/task-federation-manage.html"
      - title: Importe sua conexão federada existente
        url: "/task-federation-import.html"
    - title: Agentes de console
      entries:
      - title: Manter a VM e o SO
        url: "/task-maintain-agents.html"
      - title: Manter um agente instalado no VCenter
        url: "/task-agent-vm-config.html"
      - title: Instalar um certificado assinado pela CA para acesso ao console da
          web
        url: "/task-installing-https-cert.html"
      - title: Configurar um agente de console para usar um servidor proxy
        url: "/task-configuring-proxy.html"
      - title: Exigir o uso de IMDSv2 em instâncias EC2
        url: "/task-require-imdsv2.html"
      - title: Gerenciar atualizações de agentes
        url: "/task-upgrade-agent.html"
      - title: Trabalhar com vários agentes do Console
        url: "/task-manage-multiple-agents.html"
      - title: Solucionar problemas do agente do console
        url: "/task-troubleshoot-agent.html"
      - title: Desinstale e remova o agente do Console
        url: "/task-uninstall-agent.html"
      - title: Configuração padrão
        url: "/reference-agent-default-config.html"
      - title: Aplicar permissões ONTAP no NetApp Console
        url: "/task-ontap-access-agent.html"
    - title: Credenciais e assinaturas
      entries:
      - title: AWS
        entries:
        - title: Saiba mais sobre credenciais e permissões
          url: "/concept-accounts-aws.html"
        - title: Gerenciar credenciais e assinaturas
          url: "/task-adding-aws-accounts.html"
      - title: Azul
        entries:
        - title: Saiba mais sobre credenciais e permissões
          url: "/concept-accounts-azure.html"
        - title: Gerenciar credenciais e assinaturas
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Saiba mais sobre projetos e permissões
          url: "/concept-accounts-gcp.html"
        - title: Gerenciar credenciais e assinaturas
          url: "/task-adding-gcp-accounts.html"
      - title: Gerenciar credenciais NSS associadas a uma organização ou conta do
          NetApp Console
        url: "/task-adding-nss-accounts.html"
      - title: Gerenciar credenciais associadas ao seu login do NetApp Console
        url: "/task-manage-user-credentials.html"
    - title: Monitorar as operações do NetApp Console
      url: "/task-monitor-cm-operations.html"
  - title: Referência
    entries:
    - title: Console de manutenção do agente
      entries:
      - title: Console de manutenção do agente
        url: "/reference-agent-maint-console.html"
    - title: Permissões
      entries:
      - title: Resumo de permissões
        url: "/reference-permissions.html"
      - title: Permissões da AWS para o agente do Console
        url: "/reference-permissions-aws.html"
      - title: Permissões do Azure para o agente do Console
        url: "/reference-permissions-azure.html"
      - title: Permissões do Google Cloud para o agente do Console
        url: "/reference-permissions-gcp.html"
    - title: Portos
      entries:
      - title: Regras de grupo de segurança do agente de console na AWS
        url: "/reference-ports-aws.html"
      - title: Regras de grupo de segurança do agente de console no Azure
        url: "/reference-ports-azure.html"
      - title: Regras de firewall do agente de console no Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Portas para o agente do Console local
        url: "/reference-ports-on-prem.html"
    - title: Acesso à rede do console (legado)
      url: "/reference-networking-saas-console-previous.html"
  - title: Conhecimento e suporte
    entries:
    - title: Registre-se para obter suporte
      url: "/task-support-registration.html"
    - title: Obter ajuda
      url: "/task-get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
