---
sidebar: sidebar 
permalink: reference-iam-ransomware-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin, ransomware, ransomware resilience 
summary: O Ransomware Resilience oferece diferentes funções de usuário para gerenciar o acesso a configurações, ações e relatórios. 
---
= Funções de acesso de resiliência contra ransomware para o NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As funções de resiliência contra ransomware fornecem aos usuários acesso ao NetApp Ransomware Resilience. O Ransomware Resilience oferece suporte às seguintes funções:

**Funções de base**

* Administrador de resiliência contra ransomware - Configurar as configurações de resiliência contra ransomware; investigar e responder a alertas de criptografia
* Visualizador de resiliência de ransomware - visualize incidentes de criptografia, relatórios e configurações de descoberta


**Funções de atividade de comportamento do usuário**link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html["Detecção de atividade suspeita do usuário"^] Os alertas fornecem visibilidade de dados como eventos de atividade de arquivo; esses alertas incluem nomes de arquivos e ações de arquivo (como Ler, Gravar, Excluir, Renomear) executadas pelo usuário.  Para limitar a visibilidade desses dados, somente usuários com essas funções podem gerenciar ou visualizar esses alertas.

* Administrador de comportamento do usuário de resiliência contra ransomware - Ative a detecção de atividades suspeitas do usuário, investigue e responda a alertas de atividades suspeitas do usuário
* Visualizador de comportamento do usuário do Ransomware Resilience - Visualize alertas de atividades suspeitas do usuário



NOTE: As funções de comportamento do usuário não são funções autônomas; elas foram projetadas para serem adicionadas às funções de administrador ou visualizador do Ransomware Resilience. Para mais informações, consulte <<Funções de comportamento do usuário>>.

Consulte as tabelas a seguir para obter descrições detalhadas de cada função.



== Funções de base

A tabela a seguir descreve as ações disponíveis para as funções de administrador e visualizador do Ransomware Resilience.

[cols="40,20a,20a"]
|===
| Recurso e ação | Administrador de resiliência de ransomware | Visualizador de resiliência de ransomware 


| Ver painel e todas as guias  a| 
Sim
 a| 
Sim



| No painel, atualize o status da recomendação  a| 
Sim
 a| 
Não



| Iniciar teste gratuito  a| 
Sim
 a| 
Não



| Iniciar descoberta de cargas de trabalho  a| 
Sim
 a| 
Não



| Iniciar a redescoberta das cargas de trabalho  a| 
Sim
 a| 
Não



3+| *Na aba Proteger*: 


| Adicionar, modificar ou excluir planos de proteção para políticas de _criptografia_  a| 
Sim
 a| 
Não



| Proteja as cargas de trabalho  a| 
Sim
 a| 
Não



| Identifique a exposição a dados sensíveis com a Classificação de Dados  a| 
Sim
 a| 
Não



| Listar planos de proteção e detalhes  a| 
Sim
 a| 
Sim



| Grupos de proteção de lista  a| 
Sim
 a| 
Sim



| Ver detalhes do grupo de proteção  a| 
Sim
 a| 
Sim



| Criar, editar ou excluir grupos de proteção  a| 
Sim
 a| 
Não



| Baixar dados  a| 
Sim
 a| 
Sim



3+| *Na aba Alertas*: 


| Exibir alertas de criptografia e detalhes de alertas  a| 
Sim
 a| 
Sim



| Editar status do incidente de criptografia  a| 
Sim
 a| 
Não



| Marcar alerta de criptografia para recuperação  a| 
Sim
 a| 
Não



| Ver detalhes do incidente de criptografia  a| 
Sim
 a| 
Sim



| Descartar ou resolver incidentes de criptografia  a| 
Sim
 a| 
Não



| Obtenha a lista completa de arquivos afetados no evento de criptografia  a| 
Sim
 a| 
Não



| Baixar dados de alertas de eventos de criptografia  a| 
Sim
 a| 
Sim



| Bloquear usuário (com configuração do agente de segurança de carga de trabalho)  a| 
Sim
 a| 
Não



3+| *Na aba Recuperar*: 


| Baixar arquivos afetados pelo evento de criptografia  a| 
Sim
 a| 
Não



| Restaurar carga de trabalho do evento de criptografia  a| 
Sim
 a| 
Não



| Baixar dados de recuperação do evento de criptografia  a| 
Sim
 a| 
Sim



| Baixar relatórios do evento de criptografia  a| 
Sim
 a| 
Sim



3+| *Na aba Configurações*: 


| Adicionar ou modificar destinos de backup  a| 
Sim
 a| 
Não



| Listar destinos de backup  a| 
Sim
 a| 
Sim



| Exibir alvos SIEM conectados  a| 
Sim
 a| 
Sim



| Adicionar ou modificar alvos SIEM  a| 
Sim
 a| 
Não



| Configurar exercício de prontidão  a| 
Sim
 a| 
Não



| Iniciar, redefinir ou editar o exercício de prontidão  a| 
Sim
 a| 
Não



| Revisar o status do exercício de prontidão  a| 
Sim
 a| 
Sim



| Atualizar configuração de descoberta  a| 
Sim
 a| 
Não



| Exibir configuração de descoberta  a| 
Sim
 a| 
Sim



3+| *Na aba Relatórios*: 


| Baixar relatórios  a| 
Sim
 a| 
Sim

|===


== Funções de comportamento do usuário

Para configurar configurações de comportamento suspeito do usuário e responder a alertas, um usuário deve ter a função de administrador de comportamento do usuário de resiliência ao ransomware. Para visualizar apenas alertas de comportamento suspeito do usuário, o usuário deve ter a função de visualizador de comportamento do usuário do Ransomware Resilience.

As funções de comportamento do usuário devem ser conferidas aos usuários com privilégios de administrador ou visualizador do Ransomware Resilience existentes que precisam de acesso alink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html["configurações e alertas de atividades suspeitas do usuário"^] .  Um usuário com a função de administrador de Resiliência contra Ransomware, por exemplo, deve receber a função de administrador de comportamento de usuário de Resiliência contra Ransomware para configurar agentes de atividade do usuário e bloquear ou desbloquear usuários.  A função de administrador de comportamento do usuário de Resiliência contra Ransomware não deve ser conferida a um visualizador de Resiliência contra Ransomware.


NOTE: Para ativar a detecção de atividades suspeitas do usuário, você deve ter a função de administrador da Organização do Console.

A tabela a seguir descreve as ações disponíveis para as funções de administrador e visualizador do comportamento do usuário do Ransomware Resilience.

[cols="40,20a,20a"]
|===
| Recurso e ação | Comportamento do usuário de resiliência ao ransomware | Visualizador de comportamento do usuário de resiliência de ransomware 


3+| *Na aba Configurações*: 


| Criar, modificar ou excluir agente de atividade do usuário  a| 
Sim
 a| 
Não



| Criar ou excluir conector de diretório de usuário  a| 
Sim
 a| 
Não



| Pausar ou retomar o coletor de dados  a| 
Sim
 a| 
Não



| Execute um exercício de preparação para violação de dados  a| 
Sim
 a| 
Não



3+| *Na aba Proteger*: 


| Adicionar, modificar ou excluir planos de proteção para políticas de _comportamento suspeito do usuário_  a| 
Sim
 a| 
Não



3+| *Na aba Alertas*: 


| Ver alertas de atividade do usuário e detalhes do alerta  a| 
Sim
 a| 
Sim



| Editar status do incidente de atividade do usuário  a| 
Sim
 a| 
Não



| Marcar alerta de atividade do usuário para recuperação  a| 
Sim
 a| 
Não



| Ver detalhes do incidente de atividade do usuário  a| 
Sim
 a| 
Sim



| Descartar ou resolver incidentes de atividade do usuário  a| 
Sim
 a| 
Não



| Obtenha a lista completa de arquivos afetados por usuários suspeitos  a| 
Sim
 a| 
Sim



| Baixar dados de alertas de eventos de atividade do usuário  a| 
Sim
 a| 
Sim



| Bloquear ou desbloquear usuário  a| 
Sim
 a| 
Não



3+| *Na aba Recuperar*: 


| Baixar arquivos impactados para evento de atividade do usuário  a| 
Sim
 a| 
Não



| Restaurar carga de trabalho do evento de atividade do usuário  a| 
Sim
 a| 
Não



| Baixar dados de recuperação do evento de atividade do usuário  a| 
Sim
 a| 
Sim



| Baixar relatórios de eventos de atividade do usuário  a| 
Sim
 a| 
Sim

|===