---
sidebar: sidebar 
permalink: reference-whats-next.html 
keywords: standard mode, what you can do 
summary: Agora que você fez login e configurou o NetApp Console no modo padrão, os usuários podem criar e descobrir sistemas de armazenamento e usar os serviços de dados do NetApp . 
---
= O que você pode fazer a seguir (modo padrão)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Agora que você fez login e configurou o NetApp Console no modo padrão, os usuários podem criar e descobrir sistemas de armazenamento e usar os serviços de dados do NetApp .


TIP: Se você instalou um agente do Console no AWS, Microsoft Azure ou Google Cloud, o Console descobre automaticamente informações sobre os buckets do Amazon S3, o armazenamento de Blobs do Azure ou os buckets do Google Cloud Storage no local onde o agente está instalado.  Esses sistemas são adicionados automaticamente à página *Sistemas*.

Para obter ajuda, vá para o https://docs.netapp.com/us-en/console-family/["página inicial da documentação do NetApp Console"^] para visualizar a documentação do NetApp Console.

.Informações relacionadas
link:concept-modes.html["Modos de implantação do NetApp Console"]
