---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, https tokens, agents should remain running, Console agent 
summary: Limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportados por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações cuidadosamente. 
---
= Limitações conhecidas do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportados por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações cuidadosamente.

Essas limitações são específicas para a configuração do NEtApp Console e administração: o agente, a plataforma de software como serviço (SaaS) e muito mais.



== Limitações do agente do console



=== Possível conflito com endereços IP no intervalo 172

O NetApp Console implanta um agente com duas interfaces que têm endereços IP nos intervalos 172.17.0.0/16 e 172.18.0.0/16.

Se sua rede tiver uma sub-rede configurada com qualquer um desses intervalos, você poderá enfrentar falhas de conectividade no Console.  Por exemplo, a descoberta de clusters ONTAP locais no Console pode falhar.

Veja o artigo da Base de Conhecimentolink:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["Conflito de IP do agente com a rede existente"] para obter instruções sobre como alterar o endereço IP das interfaces do agente.



=== A descriptografia SSL não é suportada

O Console não oferece suporte a configurações de firewall que tenham a descriptografia SSL habilitada.  Se a descriptografia SSL estiver habilitada, mensagens de erro aparecerão no Console e a instância do agente será exibida como inativa.

Para maior segurança, você tem a opção delink:task-installing-https-cert.html["instalar um certificado HTTPS assinado por uma autoridade de certificação (CA)"] .



=== Página em branco ao carregar a interface do usuário local

Se você carregar o console baseado na web que está sendo executado em um agente, a interface poderá falhar ao ser exibida algumas vezes, e você verá apenas uma página em branco.

Esse problema está relacionado a um problema de cache.  A solução alternativa é usar uma sessão anônima ou privada do navegador.



=== Hosts Linux compartilhados não são suportados

O agente não é suportado em uma VM compartilhada com outros aplicativos.  A VM deve ser dedicada ao software do agente.



=== Agentes e extensões de terceiros

Agentes de terceiros ou extensões de VM não são suportados na VM do agente.
