---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: O NetApp Console, o agente do NetApp Console e os serviços de dados do NetApp exigem acesso de saída à Internet e a capacidade de entrar em contato com os endpoints necessários. 
---
= Acesso à rede para o NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Console, o agente do NetApp Console e os serviços de dados do NetApp exigem acesso de saída à Internet e a capacidade de entrar em contato com os endpoints necessários.

Você precisará configurar o acesso à rede para o seguinte:

* Computadores que acessam o NetApp Console como software como serviço (SaaS)
* Agentes de console que você instala no local ou na nuvem. Agentes de console.



NOTE: Com a versão 4.0.0, a NetApp reduziu os pontos de extremidade de rede necessários para o Console e os agentes do Console, aumentando a segurança e simplificando a implantação. É importante ressaltar que todas as implantações anteriores à versão 4.0.0 continuam com suporte total.  Embora os endpoints anteriores permaneçam disponíveis para os agentes existentes, a NetApp recomenda fortemente atualizar as regras de firewall para os endpoints atuais após confirmar as atualizações bem-sucedidas dos agentes.link:reference-networking-saas-console-previous.html["Aprenda como atualizar sua lista de endpoints."]



[[endpoints-contacted-by-netapp-console-and-console-agents]]
== Endpoints contatados pelo NetApp Console e agentes do Console

Cada agente implantado e cada computador que acessa o NetApp Console deve ter conexões com os endpoints listados abaixo.

Os agentes de console implantados no seu provedor de nuvem precisam acessar os endpoints respectivos a esse provedor de nuvem.

[cols="2*"]
|===
| Pontos finais | Propósito 


| \ https://mysupport.netapp.com | Para obter informações sobre licenciamento e enviar mensagens AutoSupport para o suporte da NetApp. 


| \ https://signin.b2c.netapp.com | Para atualizar as credenciais do NetApp Support Site (NSS) ou adicionar novas credenciais do NSS ao NetApp Console. 


| \ https://support.netapp.com | Para obter informações sobre licenciamento e enviar mensagens do AutoSupport ao suporte da NetApp, assim como receber atualizações de software para Cloud Volumes ONTAP. 


| \https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.bluexp.netapp.com \https://cdn.auth0.com | Para fornecer recursos e serviços no NetApp Console. 


 a| 
https://bluexpinfraprod.eastus2.data.azurecr.io https://bluexpinfraprod.azurecr.io https://occmclientinfragov.azurecr.us (necessário para implantações em modo restrito)
 a| 
Para obter imagens para atualizações do agente do Console.

|===


[[cloud-provider-endpoints-contacted-the-console-agent]]
== Os endpoints do provedor de nuvem contataram o agente do Console

Os agentes de console devem ter acesso a endpoints adicionais se estiverem implantados no seu provedor de nuvem.

Configure o acesso ao ponto de extremidade da rede do provedor de nuvem antes de instalar o agente do Console.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurar acesso à rede AWS para um agente do Console"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurar acesso à rede do Azure para um agente do Console"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurar o acesso à rede do Google Cloud para um agente do Console"]




[[data-services-endpoints-contacted-by-the-console-agent]]
== Pontos de extremidade de serviços de dados contatados pelo agente do Console

Alguns serviços de dados da NetApp , bem como o Cloud Volumes ONTAP, exigem que o agente tenha acesso adicional à Internet de saída.



[[endpoints-for-cloud-volumes-ontap]]
=== Pontos de extremidade para Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Endpoints para Cloud Volumes ONTAP na AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Pontos de extremidade para Cloud Volumes ONTAP no Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Pontos de extremidade para Cloud Volumes ONTAP no Google Cloud"]




[[endpoints-for-workloads]]
=== Pontos finais para cargas de trabalho

O agente do console deve ser capaz de acessar o seguinte endpoint para cargas de trabalho do NetApp .

[cols="2*"]
|===
| Pontos finais | Propósito 


 a| 
https://api.workloads.netapp.com
 a| 
O console baseado na web contata este endpoint para interagir com as APIs do Workload Factory, a fim de gerenciar e operar cargas de trabalho baseadas no FSx para ONTAP.



 a| 
\https://ws.workloads.bluexp.netapp.com
 a| 
Utilizado pelo backend do Workload Factory para consultar o agente do Console em busca de operações do ONTAP.

|===