---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: agent maintenance console, agent troubleshooting, network connectivity validation, agent validation, hardware requirements, deployment readiness, operational compliance, installation troubleshooting 
summary: Você pode usar o console de manutenção do agente do Console para validar a instalação e a configuração de um agente do Console. 
---
= Validação do agente do console com o console de manutenção no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar o console de manutenção do agente do Console para validar a instalação e a configuração de um agente do Console.



== Acesse o console de manutenção do agente

Você pode acessar o console de manutenção a partir do host do agente do console. Navegue até o seguinte diretório:

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== verificador de configuração validar

O `config-checker validate` O comando permite validar a configuração de um agente de console.

link:reference-networking-saas-console.html["Saiba mais sobre os pontos de acesso de rede necessários."] link:task-install-agent-on-prem.html#os-req-agent["Saiba mais sobre os requisitos de host."]



=== Parâmetros

`--services <comma-separated list of services to validate>`--*OBRIGATÓRIO*--

[role="quick-margin-para"]
Selecione um ou mais serviços para validar. Os nomes de serviço válidos são:

* `PLATFORM`que valida a conectividade de rede com os endpoints do Console necessários, bem como se as portas necessárias estão abertas para o agente do Console.


`--validationTypes <comma-separated list of validation types to run>`--*OBRIGATÓRIO*-- Escolha um ou mais tipos de validação para executar. Os tipos de validação válidos são:

* `NETWORK`que valida a conectividade de rede com os endpoints do Console necessários.
* `HARDWARE` que valida se o host do agente atende aos requisitos mínimos de hardware para o agente do Console.
+

NOTE: Durante a instalação, NetApp verifica se o host do agente possui pelo menos 80% do espaço de disco disponível, o que inclui 48 GB em  `/opt` e 32 GB em  `/var` (80 GB no total). Após a instalação, exige que pelo menos 20% do disco total permaneça disponível, o que inclui 12 GB em  `/opt` e 8 GB em  `/var` (20 GB no total).



`--proxy <url>`--*OPCIONAL*--

[role="quick-margin-para"]
Especifica o URL do servidor proxy a ser usado para a validação.  Necessário se o seu agente estiver configurado para usar um servidor proxy.

`--certs <paths>`--*OPCIONAL*--

[role="quick-margin-para"]
Especifica o caminho para um ou mais arquivos de certificado a serem usados para a validação.  Os arquivos de certificado devem estar no formato PEM.  Separe vários caminhos com vírgulas.  Este parâmetro é obrigatório se o seu agente usar um certificado personalizado.



=== Exemplos de validação do verificador de configuração

Os exemplos a seguir incluem a validação da conectividade de rede, portas necessárias e requisitos de hardware, juntamente com diferentes combinações de uso de um servidor proxy e certificados personalizados.

.Validação dos requisitos de conectividade de rede e hardware:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.Validação quando um servidor proxy é usado para o agente:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.Validação quando um certificado é usado para o agente:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== Ver ajuda para qualquer comando

Para visualizar a ajuda de qualquer comando, anexe `--help` ao comando.  Por exemplo, para visualizar a ajuda para o `proxy add` comando, use o seguinte comando:

[source, cli]
----
./agent-maint-console proxy add --help
----