---
sidebar: sidebar 
permalink: reference-agent-maint-console-proxy.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy. agent proxy 
summary: Você pode usar o console de manutenção do agente do Console para configurar um agente do Console para usar um servidor proxy transparente. 
---
= Comandos de proxy transparentes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar o console de manutenção do agente do Console para configurar um agente do Console para usar um servidor proxy transparente.



== Acesse o console de manutenção do agente

Você pode acessar o Console de manutenção a partir do host do agente do Console.  Navegue até o seguinte diretório:

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


=== Ver ajuda para qualquer comando

Para visualizar a ajuda de qualquer comando, anexe `--help` ao comando.  Por exemplo, para visualizar a ajuda para o `proxy add` comando, use o seguinte comando:

[source, cli]
----
./agent-maint-console proxy add --help
----


== proxy get

O `proxy get` O comando exibe informações sobre a configuração atual do servidor proxy transparente.  Para visualizar a configuração atual do servidor proxy transparente, use o seguinte comando:



=== Exemplo de obtenção de proxy

Para visualizar a configuração atual do servidor proxy transparente, use o seguinte comando:

[source, cli]
----
./agent-maint-console proxy get
----


== adicionar proxy

O `proxy add` O comando configura o agente para usar um servidor proxy transparente.



=== Parâmetros

`-c <certificate file>`

[role="quick-margin-para"]
Especifica o caminho para o arquivo de certificado do servidor proxy.  O arquivo de certificado deve estar no formato PEM. Certifique-se de que o arquivo de certificado esteja no mesmo diretório que o comando ou especifique o caminho completo para o arquivo de certificado.



=== Exemplo de adição de proxy

Para adicionar um servidor proxy transparente, use o seguinte comando, onde `/home/ubuntu/myCA1.pem` é o caminho para o arquivo de certificado do servidor proxy.  O arquivo do certificado deve estar no formato PEM:

[source, cli]
----
./agent-maint-console proxy add -c /home/ubuntu/myCA1.pem
----


== atualização de proxy

O `proxy update` Este comando permite atualizar o certificado de um proxy transparente.



=== Parâmetros

`-c <certificate file>`Especifica o caminho para o arquivo de certificado do servidor proxy.  O arquivo de certificado deve estar no formato PEM.

Certifique-se de que o arquivo de certificado esteja no mesmo diretório que o comando ou especifique o caminho completo para o arquivo de certificado.



=== Exemplo de atualização de proxy

Para atualizar o certificado de um servidor proxy transparente, use o seguinte comando, onde `/home/ubuntu/myCA1.pem` é o caminho para o novo arquivo de certificado para o servidor proxy.  O arquivo do certificado deve estar no formato PEM:

[source, cli]
----
./agent-maint-console proxy update -c /home/ubuntu/myCA1.pem
----


== remoção de proxy

O `proxy remove` O comando remove a configuração do servidor proxy transparente do agente.



=== Exemplo de remoção de proxy

Para remover o servidor proxy transparente, use o seguinte comando:

[source, cli]
----
./agent-maint-console proxy remove
----