---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, netapp console 
summary: Você precisa garantir que o Console e quaisquer agentes instalados tenham o acesso de rede correto para funcionar corretamente. 
---
= Acesso à rede para NetApp Console 3.9.55 e versões anteriores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Console, o agente do NetApp Console e os serviços de dados do NetApp exigem acesso de saída à Internet para contatar os endpoints necessários.


NOTE: Este tópico documenta o acesso à rede necessário para versões do modo padrão do NetApp Console 3.9.55 e anteriores.  Para os endpoints necessários para 4.0.0 e superior, reviselink:reference-networking-saas-console.html["os endpoints necessários para 4.0.0 e superior"] .

Você precisa configurar o acesso à rede para o seguinte:

* Computadores que acessam o NetApp Console como software como serviço (SaaS)
* Agentes de console que você instala no local ou na nuvem.




== Atualize sua lista de endpoints para a lista revisada para 4.0.0 e superior

A partir da versão 4.0.0, os agentes do Console exigem menos endpoints.  Implantações existentes anteriores à versão 4.0.0 continuam com suporte.  Após atualizar para a versão 4.0.0 ou posterior, você pode remover os endpoints antigos da sua lista de permissões quando for conveniente.

A NetApp recomenda atualizar as regras de firewall para usar a lista de endpoints revisada, que é menor, mais segura e mais fácil de gerenciar.  A NetApp elimina a necessidade de entradas curinga, e os endpoints para atualizações de agentes oferecem suporte a todos os serviços de dados.

[cols="3*"]
|===
| *Endpoints para versões 3.9.55 e anteriores* | *Pontos finais para 4.0.0 e superiores* | *Propósito* 


 a| 
* \ https://support.netapp.com
* \ https://mysupport.netapp.com

 a| 
* \ https://mysupport.netapp.com
* \ https://signin.b2c.netapp.com
* \ https://support.netapp.com

 a| 
Para licenciamento e contato com o Suporte da NetApp .



 a| 
* \https://*.api.bluexp.netapp.com
* \ https://api.bluexp.netapp.com
* \https://*.cloudmanager.cloud.netapp.com
* \ https://cloudmanager.cloud.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.netapp.com
* \https://*.console.netapp.com

 a| 
* \ https://api.bluexp.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.netapp.com
* \https://components.console.netapp.com
* \ https://cdn.auth0.com

 a| 
Para operações do dia a dia.



 a| 
* \https://*.blob.core.windows.net
* \ https://cloudmanagerinfraprod.azurecr.io

 a| 
* \ https://bluexpinfraprod.eastus2.data.azurecr.io
* \ https://bluexpinfraprod.azurecr.io

| Para obter imagens para atualizações do agente do Console. 
|===
.Passos
. Verifique se a versão do seu agente é 4.0.0 ou superior.link:task-troubleshoot-agent.html#view-the-console-agent-version["Ver versão do agente."]
. Coloque os endpoints na lista de permissões emlink:reference-networking-saas-console.html["Pontos de extremidade suportados para 4.0.0 e superior"] .
. Reinicie o serviço do gerenciador de serviços 2 em cada agente executando o seguinte comando:
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. Execute o seguinte comando e verifique se o status do agente é exibido como _ativo(em execução)_: _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. Remova os endpoints antigos da lista de permissões do seu firewall.




== Endpoints para NetApp Console e agentes de console para 3.9.55 e anteriores

Esses pontos de extremidade são usados para agentes do Console 3.9.55 e anteriores.

[cols="2*"]
|===
| Pontos finais | Propósito 


 a| 
\ https://support.netapp.com \ https://mysupport.netapp.com
 a| 
Para obter informações de licenciamento e enviar mensagens do AutoSupport para o suporte da NetApp .



 a| 
\https://\*.api.bluexp.netapp.com \ https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \ https://cloudmanager.cloud.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com
| Para fornecer recursos e serviços no NetApp Console. 


 a| 
Escolha entre dois conjuntos de pontos de extremidade:

* Opção 1 (recomendada)
+
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io

* Opção 2
+
\https://*.blob.core.windows.net \ https://cloudmanagerinfraprod.azurecr.io


 a| 
Para obter imagens para atualizações do agente do Console.

A NetApp recomenda permitir endpoints da Opção 1 no seu firewall, pois eles são mais seguros, e não permitir endpoints da Opção 2, a menos que você esteja usando o Ransomware Resilience ou o Backup and Recovery.  Observe o seguinte sobre esses pontos finais:

* Os endpoints da Option 1 são suportados nas versões 3.9.47 e superiores. Versões anteriores à 3.9.47 não oferecem compatibilidade retroativa.
* O agente do Console primeiro contata os endpoints da Opção 2. Se esses endpoints não estiverem acessíveis, ele contata automaticamente os endpoints da Opção 1.
* Se você usar o agente do Console com o NetApp Backup and Recovery ou o Ransomware Resilience, o sistema não oferecerá suporte aos endpoints da Opção 1.  Permitir pontos de extremidade da Opção 2 e não permitir a Opção 1.


|===


== Pontos de extremidade do provedor de nuvem contatados pelo agente do Console

Os agentes de console devem ter acesso a endpoints adicionais se estiverem implantados no seu provedor de nuvem.

Habilite o acesso aos endpoints do provedor de nuvem antes de instalar o agente do Console.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurar acesso à rede AWS para um agente do Console"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurar acesso à rede do Azure para um agente do Console"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurar o acesso à rede do Google Cloud para um agente do Console"]


Os pontos de extremidade do provedor de nuvem são os mesmos para todas as versões.



== Pontos de extremidade de serviços de dados contatados pelo agente do Console

O agente do Console requer acesso adicional à Internet de saída para dar suporte a alguns serviços de dados do NetApp e ao Cloud Volumes ONTAP.



=== Pontos de extremidade para Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Endpoints para Cloud Volumes ONTAP na AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Pontos de extremidade para Cloud Volumes ONTAP no Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Pontos de extremidade para Cloud Volumes ONTAP no Google Cloud"]

