---
sidebar: sidebar 
permalink: task-federation-entra-id.html 
keywords: Microsoft Entra ID, BlueXP, federation, single sign-on, SSO, identity provider, IdP, service provider-initiated SSO, domain verification, client secret, redirect URL, organization admin, 
summary: 'Federe com seu provedor de IdP do Microsoft Entra ID para habilitar o logon único (SSO) para o NetApp Console.  Isso permite que os usuários façam login usando suas credenciais corporativas.' 
---
= Federar NetApp Console com Microsoft Entra ID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Federe com seu provedor de IdP do Microsoft Entra ID para habilitar o logon único (SSO) para o NetApp Console.  Isso permite que os usuários façam login usando suas credenciais corporativas.

.Funções necessárias
A função de administrador da Federação é necessária para criar e gerenciar federações.  O visualizador da Federação pode visualizar a página da Federação.link:reference-iam-predefined-roles.html["Saiba mais sobre funções de acesso."]


NOTE: Você pode federar com seu IdP corporativo ou com o site de suporte da NetApp .  A NetApp recomenda escolher um ou outro, mas não ambos.

O NetApp oferece suporte somente a SSO iniciado pelo provedor de serviços (iniciado pelo SP).  Primeiro, você precisa configurar o provedor de identidade para confiar na NetApp como provedora de serviços.  Em seguida, você pode criar uma conexão no Console que usa a configuração do provedor de identidade.

Você pode configurar uma conexão federada com o Microsoft Entra ID para habilitar o logon único (SSO) para o Console.  O processo envolve configurar seu ID do Microsoft Entra para confiar no Console como um provedor de serviços e, em seguida, criar a conexão no Console.

.Passos
. Selecione *Administração > Identidade e acesso*.
. Selecione *Federação* para visualizar a página *Federações*.
. Selecione *Configurar nova federação*.


[discrete]
====== Detalhes do domínio

. Insira os detalhes do seu domínio:
+
.. Escolha se deseja usar um domínio verificado ou seu domínio de e-mail.  O domínio de e-mail é o domínio associado à conta com a qual você está conectado.
.. Digite o nome da federação que você está configurando.
.. Se você escolher um domínio verificado, selecione o domínio na lista.


. Selecione *Avançar*.


[discrete]
====== Método de conexão

. Para seu método de conexão, escolha *Provedor* e depois selecione *Microsoft Enterprise ID*.
. Selecione *Avançar*.


[discrete]
====== Instruções de configuração

. Configure seu ID Microsoft Entra para confiar na NetApp como provedora de serviços.  Você precisa executar esta etapa no seu servidor Microsoft Entra ID.
+
.. Use os seguintes valores ao registrar seu aplicativo Microsoft Entra ID para confiar no Console:
+
*** Para o *URL de redirecionamento*, use `https://services.cloud.netapp.com`
*** Para o *URL de resposta*, use `https://netapp-cloud-account.auth0.com/login/callback`


.. Crie um segredo do cliente para seu aplicativo Microsoft Entra ID.  Você precisará fornecer o ID do cliente, o segredo do cliente e o nome de domínio do Entra ID para concluir a federação.


. Retorne ao Console e selecione *Avançar* para criar a conexão.


[discrete]
====== Criar conexão

. Crie a conexão com o Microsoft Entra ID
+
.. Insira o ID do cliente e o segredo do cliente que você criou na etapa anterior.
.. Digite o nome de domínio do ID do Microsoft Entra.


. Selecione *Criar conexão*.  O sistema cria a conexão em poucos segundos.


[discrete]
====== Teste e habilite a conexão

. Selecione *Avançar*.
. Selecione *Testar conexão* para testar sua conexão. Você será direcionado para uma página de login para seu servidor IdP. Faça login com suas credenciais do IdP. Após efetuar o login, volte ao Console para ativar a conexão.
+

NOTE: Ao usar o Console no modo restrito, copie o URL para uma janela anônima do navegador ou para um navegador separado para fazer login no seu IdP.

. No Console, selecione *Avançar* para revisar a página de resumo.
. Configure as notificações.
+
Escolha entre sete dias ou 30 dias.  O sistema envia notificações de expiração por e-mail e as exibe no Console para qualquer usuário com as seguintes funções: Superadministrador, Administrador da organização, Administrador da federação e Visualizador da federação.

. Analise os detalhes da federação e selecione *Ativar federação*.
. Selecione *Concluir* para finalizar o processo.


Após habilitar a federação, os usuários fazem login no NetApp Console usando suas credenciais corporativas.
