---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: 'Dependendo das ações que você realizou no Console, você pode ter associado credenciais do ONTAP e credenciais do NetApp Support Site (NSS) ao seu login de usuário.  Você pode visualizar e gerenciar essas credenciais depois de associá-las.  Por exemplo, se você alterar a senha dessas credenciais, será necessário atualizar a senha no Console.' 
---
= Gerenciar credenciais associadas ao seu login do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dependendo das ações que você realizou no Console, você pode ter associado credenciais do ONTAP e credenciais do NetApp Support Site (NSS) ao seu login de usuário.  Você pode visualizar e gerenciar essas credenciais depois de associá-las.  Por exemplo, se você alterar a senha dessas credenciais, será necessário atualizar a senha no Console.



== Credenciais ONTAP

Os usuários precisam de credenciais de administrador do ONTAP para descobrir clusters do ONTAP no Console.  No entanto, o acesso ao ONTAP System Manager depende se você está ou não usando um agente de console.

.Sem um agente de console
Os usuários são solicitados a inserir suas credenciais do ONTAP para acessar o ONTAP System Manager para o cluster.  Os usuários podem optar por salvar essas credenciais no Console, o que significa que não serão solicitados a inseri-las toda vez.  As credenciais do usuário são visíveis apenas para o respectivo usuário e podem ser gerenciadas na página Credenciais do usuário.

.Com um agente de console
Por padrão, os usuários não são solicitados a inserir suas credenciais do ONTAP para acessar o ONTAP System Manager.  No entanto, um administrador do Console (com a função de administrador da organização) pode configurar o Console para solicitar que os usuários insiram suas credenciais do ONTAP .  Quando essa configuração estiver habilitada, os usuários precisarão inserir suas credenciais do ONTAP sempre.

link:task-ontap-access-agent.html["Saber mais."^]



== Credenciais NSS

As credenciais do NSS associadas ao seu login no NetApp Console permitem o registro de suporte, o gerenciamento de casos e o acesso ao Digital Advisor.

* Ao acessar *Suporte > Recursos* e se registrar para obter suporte, você será solicitado a associar as credenciais do NSS ao seu login.
+
Isso registra sua organização ou conta para suporte e ativa o direito ao suporte.  Somente um usuário em sua organização deve associar uma conta do NetApp Support Site ao seu login para se registrar para suporte e ativar o direito ao suporte.  Após a conclusão, a página *Recursos* mostrará que sua conta está registrada para suporte.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["Aprenda como se registrar para receber suporte"^]

* Ao acessar *Administração > Suporte > Gerenciamento de casos*, você será solicitado a inserir suas credenciais do NSS, caso ainda não tenha feito isso.  Esta página permite que você crie e gerencie os casos de suporte associados à sua conta NSS e à sua empresa.
* Ao acessar o Digital Advisor no Console, você será solicitado a efetuar login no Digital Advisor inserindo suas credenciais do NSS.


Observe o seguinte sobre a conta NSS associada ao seu login:

* A conta é gerenciada no nível do usuário, o que significa que ela não pode ser visualizada por outros usuários que efetuam login.
* Só pode haver uma conta NSS associada ao Digital Advisor e ao gerenciamento de casos de suporte por usuário.
* Se você estiver tentando associar uma conta do NetApp Support Site a um sistema Cloud Volumes ONTAP , só poderá escolher entre as contas NSS que foram adicionadas à organização da qual você é membro.
+
As credenciais no nível da conta NSS são diferentes da conta NSS associada ao seu login.  As credenciais de nível de conta do NSS permitem que você implante o Cloud Volumes ONTAP com BYOL, registre sistemas PAYGO e atualize seu software.

+
link:task-adding-nss-accounts.html["Saiba mais sobre como usar credenciais NSS com sua organização ou conta do NetApp Console"] .





== Gerencie suas credenciais de usuário

Gerencie suas credenciais de usuário atualizando o nome de usuário e a senha ou excluindo as credenciais.

.Passos
. Selecione *Administração > Credenciais*.
. Selecione *Credenciais do usuário*.
. Se você ainda não tiver nenhuma credencial de usuário, poderá selecionar *Adicionar credenciais NSS* para adicionar sua conta do Site de Suporte NetApp .
. Gerencie as credenciais existentes escolhendo as seguintes opções no menu Ações:
+
** *Atualizar credenciais*: Atualize o nome de usuário e a senha da conta.
** *Excluir credenciais*: Remova a conta NSS associada ao seu login do Console.



