---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'Se você for um usuário iniciante do NetApp Console, o assistente do Console o orientará no processo de configuração inicial.  O assistente ajuda você a adicionar uma conta do NetApp Support Site (NSS), adicionar um agente de console, adicionar um cluster e adicionar uma licença ou assinatura, facilitando o início do gerenciamento dos seus dados.' 
---
= Comece a usar o assistente do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se você estiver usando o NetApp Console (SaaS) pela primeira vez e tiver a função de administrador da organização, poderá usar o assistente do console para orientá-lo no processo de configuração inicial. O assistente ajuda você a adicionar uma conta do NetApp Support Site (NSS), adicionar um agente de console, adicionar um cluster e adicionar uma licença ou assinatura, facilitando o início do gerenciamento de seus dados.



== Funções necessárias para acessar o assistente do Console

O assistente do Console está disponível somente para usuários com a função de administrador da organização.

Por padrão, o NetApp Console exibe o assistente do Console na página inicial para usuários que acessam o sistema pela primeira vez e que possuem a função de administrador da organização. Ele permanecerá disponível até que você conclua as tarefas obrigatórias de criação de um agente de console e adição de um sistema.

Utilize o assistente para concluir essas tarefas, que fornecem a configuração mínima para o seu ambiente NetApp Console:

* Adicione uma conta do NetApp Support Site (NSS).
+
link:task-adding-nss-accounts.html["Aprenda como adicionar uma conta NSS"].

* Conecte-se ao seu ambiente de armazenamento implantando um agente de console.
+
link:task-install-agent-on-prem.html["Aprenda como instalar um agente de console localmente."]

* Gerencie um sistema de armazenamento adicionando ou descobrindo um cluster.
* Adicione uma assinatura de mercado ou uma licença PAYGO.
+
link:https://docs.netapp.com/us-en/console-licenses-subscriptions/index.html["Aprenda como adicionar licenças e assinaturas."^].

* Analise as informações dos serviços de dados.

