---
sidebar: sidebar 
permalink: task-federation-adfs.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: 'Federe com seus Serviços de Federação do Active Directory (AD FS) para habilitar o logon único (SSO) para o NetApp Console.  Isso permite que os usuários façam login usando suas credenciais corporativas.' 
---
= Federar o NetApp Console com os Serviços de Federação do Active Directory (AD FS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Federe seus Serviços de Federação do Active Directory (AD FS) com o NetApp Console para habilitar o logon único (SSO) para o NetApp Console.  Isso permite que os usuários façam login no Console usando suas credenciais corporativas.

.Funções necessárias
A função de administrador da Federação é necessária para criar e gerenciar federações.  O visualizador da Federação pode visualizar a página da Federação.link:reference-iam-predefined-roles.html["Saiba mais sobre funções de acesso."]


NOTE: Você pode federar com seu IdP corporativo ou com o site de suporte da NetApp .  A NetApp recomenda escolher um ou outro, mas não ambos.

O NetApp oferece suporte somente a SSO iniciado pelo provedor de serviços (iniciado pelo SP).  Primeiro, configure o provedor de identidade para confiar no NetApp Console como um provedor de serviços.  Em seguida, crie uma conexão no Console usando a configuração do seu provedor de identidade.

Você pode configurar a federação com seu servidor AD FS para habilitar o logon único (SSO) para o NetApp Console.  O processo envolve configurar o AD FS para confiar no Console como um provedor de serviços e, em seguida, criar a conexão no NetApp Console.

.Antes de começar
* É necessária uma conta IdP com privilégios administrativos.  Coordene com seu administrador do IdP para concluir as etapas.
* Identifique o domínio que você deseja usar para federação.  Você pode usar seu domínio de e-mail ou um domínio diferente que seja seu.  Se você quiser usar um domínio diferente do seu domínio de e-mail, primeiro verifique o domínio no Console.  Você pode fazer isso seguindo os passos nolink:task-federation-verify-domain.html["Verifique seu domínio no NetApp Console"] tópico.


.Passos
. Selecione *Administração > Identidade e acesso*.
. Selecione *Federação* para visualizar a página *Federações*.
. Selecione *Configurar nova federação*.
. Insira os detalhes do seu domínio:
+
.. Escolha se deseja usar um domínio verificado ou seu domínio de e-mail.  O domínio de e-mail é o domínio associado à conta com a qual você está conectado.
.. Digite o nome da federação que você está configurando.
.. Se você escolher um domínio verificado, selecione o domínio na lista.


. Selecione *Avançar*.
. Para seu método de conexão, escolha *Protocolo* e depois selecione *Serviços de Federação do Active Directory (AD FS)*.
. Selecione *Avançar*.
. Crie uma Relying Party Trust no seu servidor AD FS.  Você pode usar o PowerShell ou configurá-lo manualmente no seu servidor AD FS.  Consulte a documentação do AD FS para obter detalhes sobre como criar uma confiança de terceira parte confiável.
+
.. Crie a confiança usando o PowerShell usando o seguinte script:
+
[source, powershell]
----
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"
----
.. Como alternativa, você pode criar a confiança manualmente no console de gerenciamento do AD FS.  Use os seguintes valores do NetApp Console ao criar a confiança:
+
*** Ao criar o Relying Trust Identifier, use o valor **YOUR_TENANT**: `netapp-cloud-account`
*** Ao selecionar *Ativar suporte para WS-Federation*, use o valor **YOUR_AUTH0_DOMAIN**: `netapp-cloud-account.auth0.com`


.. Depois de criar a confiança, copie o URL de metadados do seu servidor AD FS ou baixe o arquivo de metadados da federação.  Você precisará deste URL ou arquivo para concluir a conexão no Console.


+
A NetApp recomenda usar o URL de metadados para permitir que o NetApp Console recupere automaticamente a configuração mais recente do AD FS.  Se você baixar o arquivo de metadados da federação, precisará atualizá-lo manualmente no NetApp Console sempre que houver alterações na configuração do AD FS.

. Retorne ao Console e selecione *Avançar* para criar a conexão.
. Crie a conexão com o AD FS.
+
.. Insira o *URL do AD FS* que você copiou do seu servidor AD FS na etapa anterior ou carregue o arquivo de metadados da federação que você baixou do seu servidor AD FS.


. Selecione *Criar conexão*.  A criação da conexão pode levar alguns segundos.
. Selecione *Avançar*.
. Selecione *Testar conexão* para testar sua conexão.  Você será direcionado para uma página de login para seu servidor IdP.  Efetue login com suas credenciais do IdP para concluir o teste e retorne ao Console para habilitar a conexão.
. Selecione *Avançar*.
. Na página *Habilitar federação*, revise os detalhes da federação e selecione *Habilitar federação*.
. Selecione *Concluir* para finalizar o processo.


Depois de habilitar a federação, os usuários podem fazer login no NetApp Console usando suas credenciais corporativas.
