---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: Para instalar manualmente o agente do Console no seu próprio host Linux, você precisa revisar os requisitos do host, configurar sua rede, preparar as permissões do Google Cloud, habilitar as APIs do Google Cloud, instalar o Console e, em seguida, fornecer as permissões que você preparou. 
---
= Instalar manualmente o agente do Console no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para instalar manualmente o agente do Console no seu próprio host Linux, você precisa revisar os requisitos do host, configurar sua rede, preparar as permissões do Google Cloud, habilitar as APIs do Google Cloud, instalar o Console e, em seguida, fornecer as permissões que você preparou.

.Antes de começar
* Você deveria ter umlink:concept-connectors.html["compreensão dos agentes do Console"] .
* Você deve revisarlink:reference-limitations.html["Limitações do agente do console"] .




== Etapa 1: Revise os requisitos do host

O software do agente do Console deve ser executado em um host que atenda aos requisitos específicos do sistema operacional, requisitos de RAM, requisitos de porta e assim por diante.


NOTE: O agente do Console reserva o intervalo de UID e GID de 19000 a 19200.  Este intervalo é fixo e não pode ser modificado.  Se algum software de terceiros no seu host estiver usando UIDs ou GIDs dentro desse intervalo, a instalação do agente falhará.  A NetApp recomenda usar um host livre de software de terceiros para evitar conflitos.

Host dedicado:: O agente do Console não é suportado em um host compartilhado com outros aplicativos. O host deve ser um host dedicado.  O host pode ter qualquer arquitetura que atenda aos seguintes requisitos de tamanho:
+
--
* CPU: 8 núcleos ou 8 vCPUs
* RAM: 32 GB
* Espaço em disco: 165 GB é recomendado para o host, com os seguintes requisitos de partição:
+
** `/opt`: 120 GiB de espaço devem estar disponíveis
+
O agente usa `/opt` para instalar o `/opt/application/netapp` diretório e seu conteúdo.

** `/var`: 40 GiB de espaço devem estar disponíveis
+
O agente do Console requer este espaço em `/var` porque o Docker ou o Podman são arquitetados para criar os contêineres dentro deste diretório.  Especificamente, eles criarão contêineres no `/var/lib/containers/storage` diretório.  Montagens externas ou links simbólicos não funcionam neste espaço.





--
Hipervisor:: É necessário um hipervisor bare metal ou hospedado certificado para executar um sistema operacional compatível.
[[podman-versions]]Requisitos do sistema operacional e do contêiner:: O agente do Console é compatível com os seguintes sistemas operacionais ao usar o Console no modo padrão ou no modo restrito.  Uma ferramenta de orquestração de contêineres é necessária antes de instalar o agente.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| Sistema operacional | Versões de SO suportadas | Versões de agentes suportadas | Ferramenta de contêiner necessária | SELinux a 


 a| 
Red Hat Enterprise Linux
 a| 
9.1 a 9.4

8,6 a 8,10

* Somente versões em inglês.
* O host deve ser registrado no Red Hat Subscription Management.  Se não estiver registrado, o host não poderá acessar os repositórios para atualizar o software de terceiros necessário durante a instalação do agente.

 a| 
3.9.50 ou posterior com o Console no modo padrão ou modo restrito
 a| 
Podman versão 4.6.1 ou 4.9.4

<<podman-configuration,Ver requisitos de configuração do Podman>> .
 a| 
Suportado no modo de imposição ou no modo permissivo

* O gerenciamento de sistemas Cloud Volumes ONTAP NÃO é suportado por agentes que tenham o SELinux habilitado no sistema operacional.




 a| 
Ubuntu
 a| 
24,04 LTS
 a| 
3.9.45 ou posterior com o NetApp Console no modo padrão ou restrito
 a| 
Docker Engine 23.06 para 28.0.0.
 a| 
Não suportado



 a| 
22,04 LTS
 a| 
3.9.50 ou posterior
 a| 
Docker Engine 23.0.6 para 28.0.0.
 a| 
Não suportado

|===
--
Tipo de máquina do Google Cloud:: Um tipo de instância que atende aos requisitos de CPU e RAM acima.  Recomendamos n2-standard-8.
+
--
O agente do Console é compatível com o Google Cloud em uma instância de VM com um sistema operacional compatível https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["Recursos de VM blindada"^]

--
Espaço em disco em /opt:: 100 GiB de espaço devem estar disponíveis
+
--
O agente usa `/opt` para instalar o `/opt/application/netapp` diretório e seu conteúdo.

--
Espaço em disco em /var:: 20 GiB de espaço devem estar disponíveis
+
--
O agente do Console requer este espaço em `/var` porque o Docker ou o Podman são arquitetados para criar os contêineres dentro deste diretório.  Especificamente, eles criarão contêineres no `/var/lib/containers/storage` diretório.  Montagens externas ou links simbólicos não funcionam neste espaço.

--




== Etapa 2: instalar o Podman ou o Docker Engine

Dependendo do seu sistema operacional, o Podman ou o Docker Engine é necessário antes de instalar o agente.

* O Podman é necessário para o Red Hat Enterprise Linux 8 e 9.
+
<<podman-versions,Veja as versões do Podman suportadas>> .

* O Docker Engine é necessário para o Ubuntu.
+
<<podman-versions,Veja as versões suportadas do Docker Engine>> .



.Passos
[role="tabbed-block"]
====
.Podman
--
Siga estas etapas para instalar e configurar o Podman:

* Habilite e inicie o serviço podman.socket
* Instalar python3
* Instale o pacote podman-compose versão 1.0.6
* Adicione podman-compose à variável de ambiente PATH
* Se estiver usando o Red Hat Enterprise Linux 8, verifique se sua versão do Podman está usando o DNS Aardvark em vez do CNI



NOTE: Ajuste a porta aardvark-dns (padrão: 53) após instalar o agente para evitar conflitos de porta DNS.  Siga as instruções para configurar a porta.

.Passos
. Remova o pacote podman-docker se ele estiver instalado no host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Instale o Podman.
+
Você pode obter o Podman nos repositórios oficiais do Red Hat Enterprise Linux.

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Onde <versão> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas>> .

+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Onde <versão> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas>> .

. Habilite e inicie o serviço podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Instale python3.
+
[source, cli]
----
sudo dnf install python3
----
. Instale o pacote do repositório EPEL se ele ainda não estiver disponível no seu sistema.
. Se estiver usando o Red Hat Enterprise:
+
Esta etapa é necessária porque o podman-compose está disponível no repositório Extra Packages for Enterprise Linux (EPEL).

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Instale o pacote podman-compose 1.0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Usando o `dnf install` O comando atende ao requisito de adicionar podman-compose à variável de ambiente PATH.  O comando de instalação adiciona podman-compose a /usr/bin, que já está incluído no `secure_path` opção no host.

. Se estiver usando o Red Hat Enterprise Linux 8, verifique se sua versão do Podman está usando o NetAvark com o DNS Aardvark em vez do CNI.
+
.. Verifique se o seu networkBackend está definido como CNI executando o seguinte comando:
+
[source, cli]
----
podman info | grep networkBackend
----
.. Se o networkBackend estiver definido como `CNI` , você precisará alterá-lo para `netavark` .
.. Instalar `netavark` e `aardvark-dns` usando o seguinte comando:
+
[source, cli]
----
dnf install aardvark-dns netavark
----
.. Abra o `/etc/containers/containers.conf` arquivo e modifique a opção network_backend para usar "netavark" em vez de "cni".


+
Se `/etc/containers/containers.conf` não existe, faça as alterações de configuração para `/usr/share/containers/containers.conf` .

. Reinicie o podman.
+
[source, cli]
----
systemctl restart podman
----
. Confirme se networkBackend foi alterado para "netavark" usando o seguinte comando:
+
[source, cli]
----
podman info | grep networkBackend
----


--
.Motor Docker
--
Siga a documentação do Docker para instalar o Docker Engine.

.Passos
. https://docs.docker.com/engine/install/["Ver instruções de instalação do Docker"^]
+
Siga as etapas para instalar uma versão compatível do Docker Engine.  Não instale a versão mais recente, pois ela não é suportada pelo Console.

. Verifique se o Docker está habilitado e em execução.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== Etapa 3: configurar a rede

Configure sua rede para que o agente do Console possa gerenciar recursos e processos dentro do seu ambiente de nuvem híbrida.  Por exemplo, você precisa garantir que as conexões estejam disponíveis para as redes de destino e que o acesso de saída à Internet esteja disponível.

Conexões com redes de destino:: O agente do Console requer uma conexão de rede com o local onde você planeja criar e gerenciar sistemas.  Por exemplo, a rede onde você planeja criar sistemas Cloud Volumes ONTAP ou um sistema de armazenamento em seu ambiente local.


Acesso de saída à Internet:: O local de rede onde você implanta o agente do Console deve ter uma conexão de saída com a Internet para entrar em contato com endpoints específicos.


Endpoints contatados de computadores ao usar o NetApp Console baseado na Web::
+
--
Os computadores que acessam o Console a partir de um navegador da web devem ter a capacidade de contatar vários terminais.  Você precisará usar o Console para configurar o agente do Console e para o uso diário do Console.

link:reference-networking-saas-console.html["Preparar a rede para o console NetApp"] .

--


Endpoints contatados pelo agente do Console:: O agente do Console requer acesso de saída à Internet para entrar em contato com os seguintes endpoints para gerenciar recursos e processos dentro do seu ambiente de nuvem pública para operações diárias.
+
--
Os endpoints listados abaixo são todos entradas CNAME.

[cols="2a,1a"]
|===
| Pontos finais | Propósito 


 a| 
\ https://www.googleapis.com/compute/v1/ \ https://compute.googleapis.com/compute/v1 \ https://cloudresourcemanager.googleapis.com/v1/projects \ https://www.googleapis.com/compute/beta \ https://storage.googleapis.com/storage/v1 \ https://www.googleapis.com/storage/v1 \ https://iam.googleapis.com/v1 \ https://cloudkms.googleapis.com/v1 \ https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Para gerenciar recursos no Google Cloud.



 a| 
\ https://mysupport.netapp.com
 a| 
Para obter informações de licenciamento e enviar mensagens do AutoSupport para o suporte da NetApp .



 a| 
\ https://support.netapp.com
 a| 
Para obter informações de licenciamento e enviar mensagens do AutoSupport para o suporte da NetApp .



 a| 
\ https://signin.b2c.netapp.com
 a| 
Para atualizar as credenciais do NetApp Support Site (NSS) ou adicionar novas credenciais do NSS ao NetApp Console.



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
Para fornecer recursos e serviços no NetApp Console.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Para obter imagens para atualizações do agente do Console.

* Quando você implanta um novo agente, a verificação de validação testa a conectividade com os endpoints atuais.  Se você usarlink:link:reference-networking-saas-console-previous.html["pontos finais anteriores"] , a verificação de validação falha.  Para evitar essa falha, pule a verificação de validação.
+
Embora os endpoints anteriores ainda sejam suportados, a NetApp recomenda atualizar suas regras de firewall para os endpoints atuais o mais rápido possível. link:reference-networking-saas-console-previous.html#update-endpoint-list["Aprenda como atualizar sua lista de endpoints"] .

* Quando você atualiza os endpoints atuais no seu firewall, seus agentes existentes continuarão funcionando.


|===
--


Servidor proxy:: O NetApp oferece suporte a configurações de proxy explícitas e transparentes.  Se você estiver usando um proxy transparente, você só precisa fornecer o certificado para o servidor proxy.  Se estiver usando um proxy explícito, você também precisará do endereço IP e das credenciais.
+
--
* Endereço IP
* Credenciais
* Certificado HTTPS


--


Portos:: Não há tráfego de entrada para o agente do Console, a menos que você o inicie ou se ele for usado como um proxy para enviar mensagens do AutoSupport do Cloud Volumes ONTAP para o Suporte da NetApp .
+
--
* HTTP (80) e HTTPS (443) fornecem acesso à interface de usuário local, que você usará em raras circunstâncias.
* SSH (22) só é necessário se você precisar se conectar ao host para solução de problemas.
* Conexões de entrada pela porta 3128 serão necessárias se você implantar sistemas Cloud Volumes ONTAP em uma sub-rede onde uma conexão de saída com a Internet não esteja disponível.
+
Se os sistemas Cloud Volumes ONTAP não tiverem uma conexão de saída com a Internet para enviar mensagens do AutoSupport , o Console configurará automaticamente esses sistemas para usar um servidor proxy incluído no agente do Console.  O único requisito é garantir que o grupo de segurança do agente do Console permita conexões de entrada pela porta 3128.  Você precisará abrir esta porta depois de implantar o agente do Console.



--


Habilitar NTP:: Se você estiver planejando usar o NetApp Data Classification para verificar suas fontes de dados corporativos, deverá habilitar um serviço Network Time Protocol (NTP) no agente do Console e no sistema NetApp Data Classification para que o horário seja sincronizado entre os sistemas. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Saiba mais sobre a classificação de dados da NetApp"^]




== Etapa 4: configurar permissões para o agente do Console

Uma conta de serviço do Google Cloud é necessária para fornecer ao agente do Console as permissões necessárias para que o Console gerencie recursos no Google Cloud.  Ao criar o agente do Console, você precisará associar essa conta de serviço à VM do agente do Console.

É sua responsabilidade atualizar a função personalizada à medida que novas permissões são adicionadas em versões subsequentes.  Se novas permissões forem necessárias, elas serão listadas nas notas de versão.

.Passos
. Crie uma função personalizada no Google Cloud:
+
.. Crie um arquivo YAML que inclua o conteúdo dolink:reference-permissions-gcp.html["permissões de conta de serviço para o agente do Console"] .
.. No Google Cloud, ative o Cloud Shell.
.. Faça upload do arquivo YAML que inclui as permissões necessárias.
.. Crie uma função personalizada usando o `gcloud iam roles create` comando.
+
O exemplo a seguir cria uma função chamada "conector" no nível do projeto:

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentação do Google Cloud: Criação e gerenciamento de funções personalizadas"^]



. Crie uma conta de serviço no Google Cloud e atribua a função à conta de serviço:
+
.. No serviço IAM e Admin, selecione *Contas de serviço > Criar conta de serviço*.
.. Insira os detalhes da conta de serviço e selecione *Criar e continuar*.
.. Selecione a função que você acabou de criar.
.. Conclua as etapas restantes para criar a função.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentação do Google Cloud: Criação de uma conta de serviço"^]



. Se você planeja implantar sistemas Cloud Volumes ONTAP em projetos diferentes daquele em que o agente do Console reside, será necessário fornecer à conta de serviço do agente do Console acesso a esses projetos.
+
Por exemplo, digamos que o agente do Console esteja no projeto 1 e você queira criar sistemas Cloud Volumes ONTAP no projeto 2.  Você precisará conceder acesso à conta de serviço no projeto 2.

+
.. No serviço IAM e Admin, selecione o projeto do Google Cloud onde você deseja criar sistemas Cloud Volumes ONTAP .
.. Na página *IAM*, selecione *Conceder acesso* e forneça os detalhes necessários.
+
*** Digite o e-mail da conta de serviço do agente do Console.
*** Selecione a função personalizada do agente do Console.
*** Selecione *Salvar*.




+
Para mais detalhes, consulte https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentação do Google Cloud"^]





== Etapa 5: configurar permissões de VPC compartilhadas

Se você estiver usando uma VPC compartilhada para implantar recursos em um projeto de serviço, precisará preparar suas permissões.

Esta tabela é para referência e seu ambiente deve refletir a tabela de permissões quando a configuração do IAM estiver concluída.

.Exibir permissões de VPC compartilhadas
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidade | Criador | Hospedado em | Permissões do projeto de serviço | Permissões do projeto host | Propósito 


| Conta do Google para implantar o agente | Personalizado | Projeto de Serviço  a| 
link:task-install-connector-google-bluexp-gcloud.html#agent-permissions-google["Política de implantação do agente"]
 a| 
compute.networkUser
| Implantando o agente no projeto de serviço 


| conta de serviço do agente | Personalizado | Projeto de serviço  a| 
link:reference-permissions-gcp.html["Política de conta de serviço do agente"]
| compute.networkUser gerenciador de implantação.editor | Implantando e mantendo o Cloud Volumes ONTAP e serviços no projeto de serviço 


| Conta de serviço Cloud Volumes ONTAP | Personalizado | Projeto de serviço | membro storage.admin: conta de serviço do NetApp Console como serviceAccount.user | N / D | (Opcional) Para NetApp Cloud Tiering e NetApp Backup and Recovery 


| Agente de serviço de APIs do Google | Google Cloud | Projeto de serviço  a| 
(Padrão) Editor
 a| 
compute.networkUser
| Interage com as APIs do Google Cloud em nome da implantação.  Permite que o Console use a rede compartilhada. 


| Conta de serviço padrão do Google Compute Engine | Google Cloud | Projeto de serviço  a| 
(Padrão) Editor
 a| 
compute.networkUser
| Implanta instâncias do Google Cloud e infraestrutura de computação em nome da implantação.  Permite que o Console use a rede compartilhada. 
|===
Observações:

. deploymentmanager.editor só é necessário no projeto host se você não estiver passando regras de firewall para a implantação e optar por deixar que o Console as crie para você.  O NetApp Console cria uma implantação no projeto host que contém a regra de firewall VPC0 se nenhuma regra for especificada.
. firewall.create e firewall.delete só são necessários se você não estiver passando regras de firewall para a implantação e optar por deixar que o Console as crie para você.  Essas permissões residem no arquivo .yaml da conta do Console.  Se você estiver implantando um par de HA usando uma VPC compartilhada, essas permissões serão usadas para criar as regras de firewall para VPC1, 2 e 3.  Para todas as outras implantações, essas permissões também serão usadas para criar regras para VPC0.
. Para Cloud Tiering, a conta de serviço de hierarquização deve ter a função serviceAccount.user na conta de serviço, não apenas no nível do projeto.  Atualmente, se você atribuir serviceAccount.user no nível do projeto, as permissões não serão exibidas quando você consultar a conta de serviço com getIAMPolicy.


====


== Etapa 6: habilitar as APIs do Google Cloud

Várias APIs do Google Cloud devem ser ativadas antes que você possa implantar sistemas Cloud Volumes ONTAP no Google Cloud.

.Etapa
. Ative as seguintes APIs do Google Cloud no seu projeto:
+
** API do Gerenciador de Implantação em Nuvem V2
** API de registro em nuvem
** API do Gerenciador de Recursos de Nuvem
** API do mecanismo de computação
** API de gerenciamento de identidade e acesso (IAM)
** API do Serviço de Gerenciamento de Chaves em Nuvem (KMS)
+
(Obrigatório somente se você estiver planejando usar o NetApp Backup and Recovery com chaves de criptografia gerenciadas pelo cliente (CMEK))





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Documentação do Google Cloud: Habilitando APIs"^]



== Etapa 7: instalar o agente do console

Após a conclusão dos pré-requisitos, você pode instalar manualmente o software no seu próprio host Linux.

.Antes de começar
Você deve ter o seguinte:

* Privilégios de root para instalar o agente do Console.
* Detalhes sobre um servidor proxy, caso um proxy seja necessário para acesso à Internet a partir do agente do Console.
+
Você tem a opção de configurar um servidor proxy após a instalação, mas isso requer a reinicialização do agente do Console.

* Um certificado assinado pela CA, se o servidor proxy usar HTTPS ou se o proxy for um proxy de interceptação.



NOTE: Não é possível definir um certificado para um servidor proxy transparente ao instalar manualmente o agente do Console.  Se precisar definir um certificado para um servidor proxy transparente, você deverá usar o Console de Manutenção após a instalação. Saiba mais sobre olink:reference-connector-maint-console.html["Console de manutenção do agente"] .

.Sobre esta tarefa
O instalador disponível no site de suporte da NetApp pode ser uma versão anterior.  Após a instalação, o agente do Console se atualiza automaticamente se uma nova versão estiver disponível.

.Passos
. Se as variáveis de sistema _http_proxy_ ou _https_proxy_ estiverem definidas no host, remova-as:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se você não remover essas variáveis do sistema, a instalação falhará.

. Baixe o software do agente do Console em https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de suporte da NetApp"^] e, em seguida, copie-o para o host Linux.
+
Você deve baixar o instalador do agente "online" destinado ao uso em sua rede ou na nuvem.

. Atribua permissões para executar o script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Onde <versão> é a versão do agente do Console que você baixou.

. Se estiver instalando em um ambiente de nuvem governamental, desative as verificações de configuração.link:task-troubleshoot-connector.html#disable-config-check["Aprenda como desabilitar verificações de configuração para instalações manuais."]
. Execute o script de instalação.
+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Você precisará adicionar informações de proxy se sua rede exigir um proxy para acesso à Internet.  Você pode adicionar um proxy transparente ou explícito.  Os parâmetros --proxy e --cacert são opcionais e você não será solicitado a adicioná-los.  Se você tiver um servidor proxy, precisará inserir os parâmetros conforme mostrado.

+
Aqui está um exemplo de configuração de um servidor proxy explícito com um certificado assinado por uma CA:

+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy`configura o agente do Console para usar um servidor proxy HTTP ou HTTPS usando um dos seguintes formatos:

+
** \http://endereço:porta
** \http://nome-de-usuário:senha@endereço:porta
** \http://nome-de-domínio%92nome-de-usuário:senha@endereço:porta
** \https://endereço:porta
** \https://nome-de-usuário:senha@endereço:porta
** \https://nome-de-domínio%92nome-de-usuário:senha@endereço:porta
+
Observe o seguinte:

+
*** O usuário pode ser um usuário local ou de domínio.
*** Para um usuário de domínio, você deve usar o código ASCII para um \, conforme mostrado acima.
*** O agente do Console não oferece suporte a nomes de usuário ou senhas que incluam o caractere @.
*** Se a senha incluir qualquer um dos seguintes caracteres especiais, você deverá escapar esse caractere especial colocando uma barra invertida antes dele: & ou !
+
Por exemplo:

+
\http://bxpproxyuser:netapp1\!@endereço:3128







`--cacert`especifica um certificado assinado pela CA a ser usado para acesso HTTPS entre o agente do Console e o servidor proxy.  Este parâmetro é necessário para servidores proxy HTTPS, servidores proxy de interceptação e servidores proxy transparentes.

+ Aqui está um exemplo de configuração de um servidor proxy transparente.  Ao configurar um proxy transparente, você não precisa definir o servidor proxy.  Você só adiciona um certificado assinado pela CA ao host do agente do Console:

+

[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0 --cacert /tmp/cacert/certificate.cer
----
. Se você usou o Podman, precisará ajustar a porta aardvark-dns.
+
.. SSH para a máquina virtual do agente do Console.
.. Abra o arquivo podman _/usr/share/containers/containers.conf_ e modifique a porta escolhida para o serviço DNS do Aardvark.  Por exemplo, altere para 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Reinicie a máquina virtual do agente do Console.


. Aguarde a conclusão da instalação.
+
No final da instalação, o serviço do agente do Console (occm) será reiniciado duas vezes se você tiver especificado um servidor proxy.




NOTE: Se a instalação falhar, você pode visualizar o relatório e os logs da instalação para ajudar a corrigir os problemas.link:task-troubleshoot-connector.html#troubleshoot-installation["Aprenda a solucionar problemas de instalação."]

. Abra um navegador da Web em um host que tenha uma conexão com a máquina virtual do agente do Console e insira o seguinte URL:
+
https://_ipaddress_[]

. Após efetuar login, configure o agente do Console:
+
.. Especifique a organização a ser associada ao agente do Console.
.. Digite um nome para o sistema.
.. Em *Você está executando em um ambiente seguro?* mantenha o modo restrito desabilitado.
+
Você deve manter o modo restrito desabilitado porque estas etapas descrevem como usar o Console no modo padrão.  Você deve habilitar o modo restrito somente se tiver um ambiente seguro e quiser desconectar esta conta dos serviços de backend.  Se for esse o caso,link:task-quick-start-restricted-mode.html["siga as etapas para começar a usar o NetApp Console no modo restrito"] .

.. Selecione *Vamos começar*.


+

NOTE: Se a instalação falhar, você poderá visualizar logs e um relatório para ajudar a solucionar problemas.link:task-troubleshoot-connector.html#troubleshoot-installation["Aprenda a solucionar problemas de instalação."]



Se você tiver buckets do Google Cloud Storage na mesma conta do Google Cloud onde criou o agente do Console, verá um sistema do Google Cloud Storage aparecer na página *Sistemas* automaticamente. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["Aprenda a gerenciar o Google Cloud Storage no NetApp Console"^]



== Etapa 8: fornecer permissões ao agente do console

Você precisa fornecer ao agente do Console as permissões do Google Cloud que você configurou anteriormente.  Fornecer as permissões permite que o agente do Console gerencie seus dados e infraestrutura de armazenamento no Google Cloud.

.Passos
. Acesse o portal do Google Cloud e atribua a conta de serviço à instância de VM do agente do Console.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentação do Google Cloud: Alterando a conta de serviço e os escopos de acesso de uma instância"^]

. Se você quiser gerenciar recursos em outros projetos do Google Cloud, conceda acesso adicionando a conta de serviço com a função de agente do Console a esse projeto. Você precisará repetir esta etapa para cada projeto.

