---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: Desinstale um agente do Console para solucionar problemas ou removê-lo permanentemente do host. Os passos necessários dependem do modo de implantação que você está utilizando. Depois de remover um agente do Console do seu ambiente, você pode removê-lo do Console. 
---
= Desinstale e remova um agente do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Desinstale um agente do Console para solucionar problemas ou removê-lo permanentemente do host. Os passos necessários dependem do modo de implantação que você está utilizando. Depois de remover um agente do Console do seu ambiente, você pode removê-lo do Console.



[[uninstall-the-agent-when-it-has-outbound-connectivity]]
== Desinstale o agente quando ele tiver conectividade de saída

Se você estiver usando o modo padrão ou o modo restrito (em outras palavras, o host do agente tem conectividade de saída), siga as etapas abaixo para desinstalar o agente.

.Passos
. Conecte-se à VM Linux para o agente.
. No host Linux, execute o script de desinstalação:
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_ executa o script sem solicitar sua confirmação.





[[uninstall-the-agent-when-it-has-no-outbound-connectivity]]
== Desinstale o agente quando ele não tiver conectividade de saída

Se o seu agente não tiver conectividade de saída (por exemplo, em modo privado), você deve remover manualmente o software do agente do host.

.Etapa
. Conecte-se à VM Linux para o agente do Console.
. A partir do host Linux, execute os seguintes comandos:
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. No host Linux, exclua os arquivos de imagem de contêiner antigos e não utilizados para liberar espaço no diretório /var para reinstalação.
+
[role="tabbed-block"]
====
.Podman
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




[[remove-console-agents-from-the-console]]
== Remover agentes do Console do Console

Se você excluiu uma máquina virtual de agente ou desinstalou o agente, deverá removê-la da lista de agentes no Console. Após excluir uma máquina virtual do agente ou desinstalar o software do agente, o agente exibirá o status *Desconectado* no Console.

Observe o seguinte sobre a remoção de um agente do Console:

* Esta ação não exclui a máquina virtual.
* Esta ação não pode ser revertida: depois de remover um agente do Console, você não poderá adicioná-lo novamente.


.Passos
. Selecione *Administração > Agentes*.
. Na página *Visão geral*, selecione o menu de ações para um agente desconectado e selecione *Remover agente*.
. Digite o nome do agente para confirmar e selecione *Remover*.

