---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Depois de se inscrever no NetApp Console, você pode fazer login no console baseado na Web para começar a gerenciar seus dados e infraestrutura de armazenamento. 
---
= Efetue login no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depois de se inscrever no NetApp Console, você pode fazer login no console baseado na Web para começar a gerenciar seus dados e infraestrutura de armazenamento.

Após o cadastro, o administrador da sua organização no Console precisa adicionar sua conta de usuário a uma organização antes que você possa acessar qualquer recurso. Se você fizer login, mas não visualizar nenhum recurso, entre em contato com o administrador da sua organização. link:task-user-settings.html#contact-admin["Entre em contato com o administrador da sua organização"].

.Passos
. Acesse a URL do NetApp Console. A URL depende do modo do Console que sua organização está utilizando:
+
** **Modo padrão**: Abra um navegador da web e acesse o https://console.netapp.com["NetApp Console"]
** **Modo restrito ou modo privado**: abra um navegador da web e acesse o endereço IP onde o agente do Console está instalado.


. Na página *Login*, insira o endereço de e-mail associado ao seu login.
. Dependendo do método de autenticação associado ao seu login, você será solicitado a inserir suas credenciais.
+
** Suas credenciais existentes do NetApp Support Site (NSS)
** Uma conta do NetApp Console usando seu endereço de e-mail e uma senha
** Uma conexão federada se o seu administrador tiver configurado a federação de identidades para a sua organização



