---
sidebar: sidebar 
permalink: task-organization-verify.html 
keywords: adding, creating, netapp support site account, nss, update account, update nss account, update nss credentials, delete nss account, remove nss account, change working environment, working environment nss, digital wallet, license, change system, system nss, licenses and subscriptions 
summary: Associe uma conta do NetApp Support Site à sua organização do NetApp Console para habilitar fluxos de trabalho importantes para o Cloud Volumes ONTAP.  Essas credenciais do NSS estão associadas a toda a organização. 
---
= Verifique sua organização do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se você usa Digital Advisor, precisa verificar a organização do seu Console caso sua empresa tenha várias contas comerciais com NetApp. Digital Advisor pode exibir várias contas NetApp que não estão relacionadas à sua organização do Console. Para garantir que você veja apenas os recursos associados à sua organização do Console, você pode verificar o ID comercial que deseja associar à sua organização do Console.

O Console também suporta a associação de uma conta NSS por conta de usuário. link:task-manage-user-credentials.html["Aprenda a gerenciar credenciais em nível de usuário"] .



== Antes de começar

Você precisa ter a função de administrador da organização para verificar sua organização e seu usuário também precisa estar associado a uma conta do site de suporte da NetApp (NSS). link:task-adding-nss-accounts["Aprenda como associar sua conta NSS"].


NOTE: Se sua empresa tiver apenas uma conta comercial e seu usuário estiver associado a uma conta do NetApp Support Site, sua organização será verificada automaticamente.



== Verifique sua organização

.Passos
. Se o seu usuário tiver acesso a mais de uma organização, selecione a organização que deseja verificar no menu suspenso Organization.
. Em *Administração > Identidade e acesso*.
. Selecione *Organização*.

