---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions 
summary: Gerencie os membros da sua organização para fornecer permissões em diferentes níveis da hierarquia de recursos da sua organização. 
---
= Adicionar usuários a uma organização do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
No Console, você concede aos usuários acesso a projetos ou pastas de acordo com uma função de acesso. Uma _função de acesso_ contém um conjunto de permissões que permite a um membro (usuário ou conta de serviço) executar ações específicas no nível atribuído da hierarquia de recursos.

.Funções de acesso necessárias
Superadministrador, administrador da organização ou administrador de pasta ou projeto (para pastas e projetos que eles administram). link:reference-iam-predefined-roles.html["Saiba mais sobre funções de acesso"].



== Entenda como o acesso é concedido no NetApp Console.

O NetApp Console utiliza o controle de acesso baseado em funções (RBAC) para gerenciar permissões. Atribua funções aos usuários individualmente ou por meio de grupos federados. Cada função define as ações permitidas para recursos específicos.

Observe o seguinte sobre como conceder acesso no NetApp Console:

* Todos os usuários devem primeiro se cadastrar no NetApp Console antes de obterem acesso aos recursos.
* Você deve atribuir explicitamente uma função a cada usuário no Console antes que ele possa acessar os recursos, mesmo que seja membro de um grupo federado ao qual já tenha sido atribuída uma função.
* Você pode adicionar contas de serviço diretamente do Console e atribuir funções a elas.




== Adicionar membros à sua organização

O NetApp Console suporta três tipos de membros: contas de usuário, contas de serviço e grupos federados.

Os usuários precisam se cadastrar no NetApp Console antes que você possa adicioná-los e atribuir uma função, mesmo que estejam em um grupo federado. Crie contas de serviço diretamente no Console.

Todos os membros devem ter pelo menos uma função explicitamente atribuída a eles para poderem acessar os recursos.

Ao adicionar um membro, escolha o nível de recurso (organização, pasta ou projeto) e atribua uma ou mais funções com as permissões necessárias.



=== Adicionar um usuário

Os usuários se cadastram no NetApp Console, mas um administrador da organização, pasta ou projeto precisa adicioná-los à organização, pasta ou projeto para que possam acessar os recursos.

.Antes de começar:
O usuário já deve ter se cadastrado no NetApp Console. Se eles ainda não se inscreveram, oriente-os a... link:task-sign-up-saas.html["Inscreva-se no NetApp Console."]


NOTE: Se você estiver adicionando um usuário que faz parte de um grupo federado, certifique-se de que ele já tenha se cadastrado no NetApp Console e que uma função tenha sido explicitamente atribuída a ele no Console. A NetApp recomenda atribuir uma função de acesso mínima, como a de visualizador da organização.

.Passos
. Selecione *Administração > Identidade e acesso*.
. Selecione *Membros*.
. Selecione *Adicionar um membro*.
. Para *Tipo de membro*, mantenha *Usuário* selecionado.
. Em *E-mail do usuário*, insira o endereço de e-mail do usuário associado ao login que ele criou.
. Use a seção *Selecione uma organização, pasta ou projeto* para escolher o nível da hierarquia de recursos para o qual o membro deve ter permissões.
+
Observe o seguinte:

+
** Você pode selecionar apenas as pastas e os projetos para os quais você tem permissão.
** Ao selecionar uma organização ou pasta, você concede ao membro permissões para acessar todo o seu conteúdo.
** Você só pode atribuir a função *Administrador da organização* no nível da organização.


. *Selecione uma categoria* e depois selecione uma *Função* que forneça ao membro permissões para os recursos associados à organização, pasta ou projeto que você selecionou.
+
link:reference-iam-predefined-roles.html["Saiba mais sobre funções de acesso"] .

. Para conceder acesso a mais pastas, projetos ou funções, selecione *Adicionar função*, escolha a categoria de pasta, projeto ou função e selecione uma função.
. Selecione *Adicionar*.
+
O console envia instruções ao usuário por e-mail.





=== Adicionar uma conta de serviço

As contas de serviço permitem automatizar tarefas e conectar-se com segurança às APIs do Console. Escolha um ID e um segredo do cliente para configurações simples ou um JWT (JSON Web Token) para maior segurança em ambientes automatizados ou nativos da nuvem. Selecione o método que atenda aos seus requisitos de segurança.

.Antes de começar:
Para autenticação JWT, prepare sua chave pública ou certificado.

.Passos
. Selecione *Administração > Identidade e acesso*.
. Selecione *Membros*.
. Selecione *Adicionar um membro*.
. Para *Tipo de membro*, selecione *Conta de serviço*.
. Insira um nome para a conta de serviço.
. Para usar a autenticação JWT, selecione *Usar autenticação JWT com chave privada* e carregue sua chave ou certificado RSA público. Ignore se estiver usando ID e segredo do cliente.
+
Seu certificado X.509. Deve estar no formato PEM, CRT ou CER.

+
.. Configure notificações de expiração para o seu certificado.  Escolha entre sete dias ou 30 dias.  As notificações de expiração são enviadas por e-mail e exibidas no Console para usuários com a função de Superadministrador ou Administrador da Organização.


. Use a seção *Selecione uma organização, pasta ou projeto* para escolher o nível da hierarquia de recursos para o qual o membro deve ter permissões.
+
Observe o seguinte:

+
** Você só pode selecionar pastas e projetos para os quais você tem permissão.
** Selecionar uma organização ou pasta concede ao membro permissões para todo o seu conteúdo.
** Você só pode atribuir a função *Administrador da organização* no nível da organização.


. Selecione uma *Categoria* e, em seguida, selecione uma *Função* que conceda ao membro permissões para os recursos na organização, pasta ou projeto que você selecionou.
+
link:reference-iam-predefined-roles.html["Saiba mais sobre funções de acesso"] .

. Para conceder acesso a mais pastas, projetos ou funções, selecione *Adicionar função*, escolha a categoria de pasta, projeto ou função e selecione uma função.
. Se você não escolheu usar a autenticação JWT, baixe ou copie o ID do cliente e o segredo do cliente.
+
O Console exibe o segredo do cliente apenas uma vez. Faça uma cópia segura; você poderá recriá-la mais tarde, caso a perca.

. Se você escolheu a autenticação JWT, baixe ou copie o ID do cliente e o público-alvo do JWT. O Console exibe essas informações apenas uma vez e não permite que você as recupere posteriormente.
. Selecione *Fechar*.




== Adicione um grupo federado à sua organização.

Você pode adicionar um grupo federado do seu provedor de identidade (IdP) à sua organização e atribuir a ele uma ou mais funções. Os membros do grupo federado herdam as funções que você atribui ao grupo no Console.


IMPORTANT: Ao adicionar um grupo federado ao Console e atribuir uma função a ele, somente os usuários que são membros do grupo no seu IdP e que já se inscreveram no NetApp Console e tiveram uma função explicitamente atribuída no Console podem acessar os recursos. NetApp recomenda atribuir uma função de acesso mínima, como visualizador da organização, a esses usuários.

Antes de atribuir uma função a um grupo federado, certifique-se do seguinte:

* Configure a federação entre seu IdP e o Console. link:concept-federation.html["Aprenda como configurar a federação."]
* O grupo já deve existir no seu IdP e ter recebido acesso ao Console.


.Passos
. Selecione *Administração > Identidade e acesso*.
. Selecione *Membros*.
. Selecione *Adicionar um membro*.
. Em *Tipo de membro*, selecione *Grupo federado*.
. Selecione a federação à qual o grupo pertence.
. Em *Nome do grupo*, insira o nome exato do grupo em seu IdP.
. Use a seção *Selecione uma organização, pasta ou projeto* para escolher o nível da hierarquia de recursos para o qual o membro deve ter permissões.
+
Observe o seguinte:

+
** Você só pode selecionar pastas e projetos para os quais você tem permissão.
** Selecionar uma organização ou pasta concede ao membro permissões para todo o seu conteúdo.
** Você só pode atribuir a função *Administrador da organização* no nível da organização.


. Selecione uma *Categoria* e, em seguida, selecione uma *Função* que conceda ao membro permissões para os recursos na organização, pasta ou projeto que você selecionou.
+
link:reference-iam-predefined-roles.html["Saiba mais sobre funções de acesso"] .

. Para conceder acesso a mais pastas, projetos ou funções, selecione *Adicionar função*, escolha a categoria de pasta, projeto ou função e selecione uma função.




== Informações relacionadas

* link:concept-identity-and-access-management.html["Saiba mais sobre gerenciamento de identidade e acesso no NetApp Console"]
* link:task-iam-get-started.html["Comece com identidade e acesso"]
* link:reference-iam-predefined-roles.html["Funções de acesso ao NetApp Console"]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["Saiba mais sobre a API para identidade e acesso"^]

