---
sidebar: sidebar 
permalink: task-install-agent-aws-manual.html 
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, aws marketplace, manual install, create connector 
summary: Você pode instalar manualmente um agente do Console em um host Linux em execução na AWS.  Para instalar manualmente o agente do Console no seu próprio host Linux, você precisa revisar os requisitos do host, configurar sua rede, preparar as permissões da AWS, instalar o agente do Console e, em seguida, fornecer as permissões que você preparou. 
---
= Instalar manualmente o agente do Console na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode instalar manualmente um agente do Console em um host Linux em execução na AWS.  Para instalar manualmente o agente do Console no seu próprio host Linux, você precisa revisar os requisitos do host, configurar sua rede, preparar as permissões da AWS, instalar o agente do Console e, em seguida, fornecer as permissões que você preparou.

.Antes de começar
* Você deveria ter umlink:concept-agents.html["compreensão dos agentes do Console"] .
* Você deve revisarlink:reference-limitations.html["Limitações do agente do console"] .




== Etapa 1: Revise os requisitos do host

O software do agente do Console deve ser executado em um host que atenda aos requisitos específicos do sistema operacional, requisitos de RAM, requisitos de porta e assim por diante.


NOTE: O agente do Console reserva o intervalo de UID e GID de 19000 a 19200.  Este intervalo é fixo e não pode ser modificado.  Se algum software de terceiros no seu host estiver usando UIDs ou GIDs dentro desse intervalo, a instalação do agente falhará.  A NetApp recomenda usar um host livre de software de terceiros para evitar conflitos.

Host dedicado:: O agente do Console não é suportado em um host compartilhado com outros aplicativos. O host deve ser um host dedicado.  O host pode ter qualquer arquitetura que atenda aos seguintes requisitos de tamanho:
+
--
* CPU: 8 núcleos ou 8 vCPUs
* RAM: 32 GB
* Espaço em disco: 165 GB é recomendado para o host, com os seguintes requisitos de partição:
+
** `/opt`: 120 GiB de espaço devem estar disponíveis
+
O agente usa `/opt` para instalar o `/opt/application/netapp` diretório e seu conteúdo.

** `/var`: 40 GiB de espaço devem estar disponíveis
+
O agente do Console requer este espaço em `/var` porque o Docker ou o Podman são arquitetados para criar os contêineres dentro deste diretório.  Especificamente, eles criarão contêineres no `/var/lib/containers/storage` diretório.  Montagens externas ou links simbólicos não funcionam neste espaço.





--
Hipervisor:: É necessário um hipervisor bare metal ou hospedado certificado para executar um sistema operacional compatível.
[[podman-versions]]Requisitos do sistema operacional e do contêiner:: O agente do Console é compatível com os seguintes sistemas operacionais ao usar o Console no modo padrão ou no modo restrito.  Uma ferramenta de orquestração de contêineres é necessária antes de instalar o agente.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| Sistema operacional | Versões de SO suportadas | Versões de agentes suportadas | Ferramenta de contêiner necessária | SELinux a 


 a| 
Red Hat Enterprise Linux
 a| 
9.1 a 9.4

8,6 a 8,10

* Somente versões em inglês.
* O host deve ser registrado no Red Hat Subscription Management.  Se não estiver registrado, o host não poderá acessar os repositórios para atualizar o software de terceiros necessário durante a instalação do agente.

 a| 
3.9.50 ou posterior com o Console no modo padrão ou modo restrito
 a| 
Podman versão 4.6.1 ou 4.9.4

<<podman-configuration,Ver requisitos de configuração do Podman>> .
 a| 
Suportado no modo de imposição ou no modo permissivo

* O gerenciamento de sistemas Cloud Volumes ONTAP NÃO é suportado por agentes que tenham o SELinux habilitado no sistema operacional.




 a| 
Ubuntu
 a| 
24,04 LTS
 a| 
3.9.45 ou posterior com o NetApp Console no modo padrão ou restrito
 a| 
Docker Engine 23.06 para 28.0.0.
 a| 
Não suportado



 a| 
22,04 LTS
 a| 
3.9.50 ou posterior
 a| 
Docker Engine 23.0.6 para 28.0.0.
 a| 
Não suportado

|===
--
Tipo de instância AWS EC2:: Um tipo de instância que atende aos requisitos de CPU e RAM acima.  Recomendamos t3.2xlarge.
Par de chaves:: Ao criar o agente do Console, você precisará selecionar um par de chaves EC2 para usar com a instância.
Limite de salto de resposta PUT ao usar IMDSv2:: Se o IMDSv2 estiver habilitado na instância EC2 (esta é a configuração padrão para novas instâncias EC2), você deverá alterar o limite de salto de resposta PUT na instância para 3.  Se você não alterar o limite na instância do EC2, receberá um erro de inicialização da interface do usuário ao tentar configurar o agente.
+
--
* link:task-require-imdsv2.html["Exigir o uso do IMDSv2 em instâncias do Amazon EC2"]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html#modify-PUT-response-hop-limit["Documentação da AWS: Alterar o limite de salto de resposta PUT"^]


--
Espaço em disco em /opt:: 100 GiB de espaço devem estar disponíveis
+
--
O agente usa `/opt` para instalar o `/opt/application/netapp` diretório e seu conteúdo.

--
Espaço em disco em /var:: 20 GiB de espaço devem estar disponíveis
+
--
O agente do Console requer este espaço em `/var` porque o Docker ou o Podman são arquitetados para criar os contêineres dentro deste diretório.  Especificamente, eles criarão contêineres no `/var/lib/containers/storage` diretório.  Montagens externas ou links simbólicos não funcionam neste espaço.

--




== Etapa 2: instalar o Podman ou o Docker Engine

Dependendo do seu sistema operacional, o Podman ou o Docker Engine é necessário antes de instalar o agente.

* O Podman é necessário para o Red Hat Enterprise Linux 8 e 9.
+
<<podman-versions,Veja as versões do Podman suportadas>> .

* O Docker Engine é necessário para o Ubuntu.
+
<<podman-versions,Veja as versões suportadas do Docker Engine>> .



.Passos
[role="tabbed-block"]
====
.Podman
--
Siga estas etapas para instalar e configurar o Podman:

* Habilite e inicie o serviço podman.socket
* Instalar python3
* Instale o pacote podman-compose versão 1.0.6
* Adicione podman-compose à variável de ambiente PATH
* Se estiver usando o Red Hat Enterprise Linux, verifique se sua versão do Podman está usando o DNS Netavark Aardvark em vez do CNI



NOTE: Ajuste a porta aardvark-dns (padrão: 53) após instalar o agente para evitar conflitos de porta DNS.  Siga as instruções para configurar a porta.

.Passos
. Remova o pacote podman-docker se ele estiver instalado no host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Instale o Podman.
+
Você pode obter o Podman nos repositórios oficiais do Red Hat Enterprise Linux.

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Onde <versão> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas>> .

+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Onde <versão> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas>> .

. Habilite e inicie o serviço podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Instale python3.
+
[source, cli]
----
sudo dnf install python3
----
. Instale o pacote do repositório EPEL se ele ainda não estiver disponível no seu sistema.
. Se estiver usando o Red Hat Enterprise:
+
Esta etapa é necessária porque o podman-compose está disponível no repositório Extra Packages for Enterprise Linux (EPEL).

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Instale o pacote podman-compose 1.0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Usando o `dnf install` O comando atende ao requisito de adicionar podman-compose à variável de ambiente PATH.  O comando de instalação adiciona podman-compose a /usr/bin, que já está incluído no `secure_path` opção no host.

. Se estiver usando o Red Hat Enterprise Linux 8, verifique se sua versão do Podman está usando o NetAvark com o DNS Aardvark em vez do CNI.
+
.. Verifique se o seu networkBackend está definido como CNI executando o seguinte comando:
+
[source, cli]
----
podman info | grep networkBackend
----
.. Se o networkBackend estiver definido como `CNI` , você precisará alterá-lo para `netavark` .
.. Instalar `netavark` e `aardvark-dns` usando o seguinte comando:
+
[source, cli]
----
dnf install aardvark-dns netavark
----
.. Abra o `/etc/containers/containers.conf` arquivo e modifique a opção network_backend para usar "netavark" em vez de "cni".


+
Se `/etc/containers/containers.conf` não existe, faça as alterações de configuração para `/usr/share/containers/containers.conf` .

. Reinicie o podman.
+
[source, cli]
----
systemctl restart podman
----
. Confirme se networkBackend foi alterado para "netavark" usando o seguinte comando:
+
[source, cli]
----
podman info | grep networkBackend
----


--
.Motor Docker
--
Siga a documentação do Docker para instalar o Docker Engine.

.Passos
. https://docs.docker.com/engine/install/["Ver instruções de instalação do Docker"^]
+
Siga as etapas para instalar uma versão compatível do Docker Engine.  Não instale a versão mais recente, pois ela não é suportada pelo Console.

. Verifique se o Docker está habilitado e em execução.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== Etapa 3: configurar a rede

Certifique-se de que o local de rede onde você planeja instalar o agente do Console suporte os seguintes requisitos.  Atender a esses requisitos permite que o agente do Console gerencie recursos e processos dentro do seu ambiente de nuvem híbrida.

Conexões com redes de destino:: O agente do Console requer uma conexão de rede com o local onde você planeja criar e gerenciar sistemas.  Por exemplo, a rede onde você planeja criar sistemas Cloud Volumes ONTAP ou um sistema de armazenamento em seu ambiente local.


Acesso de saída à Internet:: O local de rede onde você implanta o agente do Console deve ter uma conexão de saída com a Internet para entrar em contato com endpoints específicos.


Endpoints contatados de computadores ao usar o NetApp Console baseado na Web::
+
--
Os computadores que acessam o Console a partir de um navegador da web devem ter a capacidade de contatar vários terminais.  Você precisará usar o Console para configurar o agente do Console e para o uso diário do Console.

link:reference-networking-saas-console.html["Preparar a rede para o console NetApp"] .

--


Endpoints contatados pelo agente do Console:: O agente do Console requer acesso de saída à Internet para entrar em contato com os seguintes endpoints para gerenciar recursos e processos dentro do seu ambiente de nuvem pública para operações diárias.
+
--
Os endpoints listados abaixo são todos entradas CNAME.

[cols="2a,1a"]
|===
| Pontos finais | Propósito 


 a| 
Serviços da AWS (amazonaws.com):

* CloudFormation
* Nuvem de Computação Elástica (EC2)
* Gerenciamento de Identidade e Acesso (IAM)
* Serviço de Gerenciamento de Chaves (KMS)
* Serviço de Token de Segurança (STS)
* Serviço de Armazenamento Simples (S3)

 a| 
Para gerenciar recursos da AWS.  O ponto de extremidade depende da sua região da AWS. https://docs.aws.amazon.com/general/latest/gr/rande.html["Consulte a documentação da AWS para obter detalhes"^]



 a| 
\ https://mysupport.netapp.com
 a| 
Para obter informações de licenciamento e enviar mensagens do AutoSupport para o suporte da NetApp .



 a| 
\ https://signin.b2c.netapp.com
 a| 
Para atualizar as credenciais do NetApp Support Site (NSS) ou adicionar novas credenciais do NSS ao NetApp Console.



 a| 
\ https://support.netapp.com
 a| 
Para obter informações de licenciamento e enviar mensagens do AutoSupport para o suporte da NetApp , bem como receber atualizações de software para o Cloud Volumes ONTAP.



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
Para fornecer recursos e serviços no NetApp Console.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Para obter imagens para atualizações do agente do Console.

* Quando você implanta um novo agente, a verificação de validação testa a conectividade com os endpoints atuais. Se você usarlink:reference-networking-saas-console-previous.html["pontos finais anteriores"] , a verificação de validação falha. Para evitar essa falha, pule a verificação de validação.
+
Embora os endpoints anteriores ainda sejam suportados, a NetApp recomenda atualizar suas regras de firewall para os endpoints atuais o mais rápido possível. link:reference-networking-saas-console-previous.html#update-endpoint-list["Aprenda como atualizar sua lista de endpoints"] .

* Quando você atualiza os endpoints atuais no seu firewall, seus agentes existentes continuarão funcionando.


|===
--


Servidor proxy:: O NetApp oferece suporte a configurações de proxy explícitas e transparentes.  Se você estiver usando um proxy transparente, você só precisa fornecer o certificado para o servidor proxy.  Se estiver usando um proxy explícito, você também precisará do endereço IP e das credenciais.
+
--
* Endereço IP
* Credenciais
* Certificado HTTPS


--


Portos:: Não há tráfego de entrada para o agente do Console, a menos que você o inicie ou se ele for usado como um proxy para enviar mensagens do AutoSupport do Cloud Volumes ONTAP para o Suporte da NetApp .
+
--
* HTTP (80) e HTTPS (443) fornecem acesso à interface de usuário local, que você usará em raras circunstâncias.
* SSH (22) só é necessário se você precisar se conectar ao host para solução de problemas.
* Conexões de entrada pela porta 3128 serão necessárias se você implantar sistemas Cloud Volumes ONTAP em uma sub-rede onde uma conexão de saída com a Internet não esteja disponível.
+
Se os sistemas Cloud Volumes ONTAP não tiverem uma conexão de saída com a Internet para enviar mensagens do AutoSupport , o Console configurará automaticamente esses sistemas para usar um servidor proxy incluído no agente do Console.  O único requisito é garantir que o grupo de segurança do agente do Console permita conexões de entrada pela porta 3128.  Você precisará abrir esta porta depois de implantar o agente do Console.



--


Habilitar NTP:: Se você planeja usar o NetApp Data Classification para verificar suas fontes de dados corporativos, habilite um serviço Network Time Protocol (NTP) no agente do Console e no sistema NetApp Data Classification para que o horário seja sincronizado entre os sistemas. https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Saiba mais sobre a classificação de dados da NetApp"^]




== Etapa 4: configurar permissões da AWS para o console

Você precisa fornecer permissões da AWS para o NetApp Console usando uma das seguintes opções:

* Opção 1: Crie políticas do IAM e anexe-as a uma função do IAM que você pode associar à instância do EC2.
* Opção 2: forneça ao Console a chave de acesso da AWS para um usuário do IAM que tenha as permissões necessárias.


Siga as etapas para preparar permissões para o Console.

[role="tabbed-block"]
====
.Função IAM
--
.Passos
. Faça login no console da AWS e navegue até o serviço IAM.
. Crie uma política:
+
.. Selecione *Políticas > Criar política*.
.. Selecione *JSON* e copie e cole o conteúdo dolink:reference-permissions-aws.html["Política do IAM para o agente do Console"] .
.. Conclua as etapas restantes para criar a política.
+
Dependendo dos serviços de dados da NetApp que você planeja usar, pode ser necessário criar uma segunda política.  Para regiões padrão, as permissões são distribuídas em duas políticas.  Duas políticas são necessárias devido ao limite máximo de tamanho de caracteres para políticas gerenciadas na AWS. link:reference-permissions-aws.html["Saiba mais sobre as políticas do IAM para o agente do Console"] .



. Crie uma função do IAM:
+
.. Selecione *Funções > Criar função*.
.. Selecione *Serviço AWS > EC2*.
.. Adicione permissões anexando a política que você acabou de criar.
.. Conclua as etapas restantes para criar a função.




.Resultado
Agora você tem uma função do IAM que pode ser associada à instância do EC2 após instalar o agente do Console.

--
.Chave de acesso AWS
--
.Passos
. Faça login no console da AWS e navegue até o serviço IAM.
. Crie uma política:
+
.. Selecione *Políticas > Criar política*.
.. Selecione *JSON* e copie e cole o conteúdo dolink:reference-permissions-aws.html["Política do IAM para o agente do Console"] .
.. Conclua as etapas restantes para criar a política.
+
Dependendo dos serviços de dados da NetApp que você planeja usar, pode ser necessário criar uma segunda política.

+
Para regiões padrão, as permissões são distribuídas em duas políticas.  Duas políticas são necessárias devido ao limite máximo de tamanho de caracteres para políticas gerenciadas na AWS. link:reference-permissions-aws.html["Saiba mais sobre as políticas do IAM para o agente do Console"] .



. Anexe as políticas a um usuário do IAM.
+
** https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html["Documentação da AWS: Criando funções do IAM"^]
** https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["Documentação da AWS: Adicionando e removendo políticas do IAM"^]


. Certifique-se de que o usuário tenha uma chave de acesso que você possa adicionar ao NetApp Console após instalar o agente do Console.


.Resultado
Agora você tem um usuário do IAM que tem as permissões necessárias e uma chave de acesso que você pode fornecer ao Console.

--
====


== Etapa 5: instalar o agente do console

Após a conclusão dos pré-requisitos, você pode instalar manualmente o software no seu próprio host Linux.

.Antes de começar
Você deve ter o seguinte:

* Privilégios de root para instalar o agente do Console.
* Detalhes sobre um servidor proxy, caso um proxy seja necessário para acesso à Internet a partir do agente do Console.
+
Você tem a opção de configurar um servidor proxy após a instalação, mas isso requer a reinicialização do agente do Console.

* Um certificado assinado pela CA, se o servidor proxy usar HTTPS ou se o proxy for um proxy de interceptação.



NOTE: Não é possível definir um certificado para um servidor proxy transparente ao instalar manualmente o agente do Console.  Se precisar definir um certificado para um servidor proxy transparente, você deverá usar o Console de Manutenção após a instalação. Saiba mais sobre olink:reference-agent-maint-console.html["Console de manutenção do agente"] .

.Sobre esta tarefa
O instalador disponível no site de suporte da NetApp pode ser uma versão anterior.  Após a instalação, o agente do Console se atualiza automaticamente se uma nova versão estiver disponível.

.Passos
. Se as variáveis de sistema _http_proxy_ ou _https_proxy_ estiverem definidas no host, remova-as:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se você não remover essas variáveis do sistema, a instalação falhará.

. Baixe o software do agente do Console em https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de suporte da NetApp"^] e, em seguida, copie-o para o host Linux.
+
Você deve baixar o instalador do agente "online" destinado ao uso em sua rede ou na nuvem.

. Atribua permissões para executar o script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Onde <versão> é a versão do agente do Console que você baixou.

. Se estiver instalando em um ambiente de nuvem governamental, desative as verificações de configuração.link:task-troubleshoot-agent.html#disable-config-check["Aprenda como desabilitar verificações de configuração para instalações manuais."]
. Execute o script de instalação.
+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Você precisará adicionar informações de proxy se sua rede exigir um proxy para acesso à Internet.  Você pode adicionar um proxy transparente ou explícito.  Os parâmetros --proxy e --cacert são opcionais e você não será solicitado a adicioná-los.  Se você tiver um servidor proxy, precisará inserir os parâmetros conforme mostrado.

+
Aqui está um exemplo de configuração de um servidor proxy explícito com um certificado assinado por uma CA:

+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy`configura o agente do Console para usar um servidor proxy HTTP ou HTTPS usando um dos seguintes formatos:

+
** \http://endereço:porta
** \http://nome-de-usuário:senha@endereço:porta
** \http://nome-de-domínio%92nome-de-usuário:senha@endereço:porta
** \https://endereço:porta
** \https://nome-de-usuário:senha@endereço:porta
** \https://nome-de-domínio%92nome-de-usuário:senha@endereço:porta
+
Observe o seguinte:

+
*** O usuário pode ser um usuário local ou de domínio.
*** Para um usuário de domínio, você deve usar o código ASCII para um \, conforme mostrado acima.
*** O agente do Console não oferece suporte a nomes de usuário ou senhas que incluam o caractere @.
*** Se a senha incluir qualquer um dos seguintes caracteres especiais, você deverá escapar esse caractere especial colocando uma barra invertida antes dele: & ou !
+
Por exemplo:

+
\http://bxpproxyuser:netapp1\!@endereço:3128







`--cacert`especifica um certificado assinado pela CA a ser usado para acesso HTTPS entre o agente do Console e o servidor proxy.  Este parâmetro é necessário para servidores proxy HTTPS, servidores proxy de interceptação e servidores proxy transparentes.

+ Aqui está um exemplo de configuração de um servidor proxy transparente.  Ao configurar um proxy transparente, você não precisa definir o servidor proxy.  Você só adiciona um certificado assinado pela CA ao host do agente do Console:

+

[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0 --cacert /tmp/cacert/certificate.cer
----
. Se você usou o Podman, precisará ajustar a porta aardvark-dns.
+
.. SSH para a máquina virtual do agente do Console.
.. Abra o arquivo podman _/usr/share/containers/containers.conf_ e modifique a porta escolhida para o serviço DNS do Aardvark.  Por exemplo, altere para 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Reinicie a máquina virtual do agente do Console.


. Aguarde a conclusão da instalação.
+
No final da instalação, o serviço do agente do Console (occm) será reiniciado duas vezes se você tiver especificado um servidor proxy.




NOTE: Se a instalação falhar, você pode visualizar o relatório e os logs da instalação para ajudar a corrigir os problemas.link:task-troubleshoot-agent.html#troubleshoot-installation["Aprenda a solucionar problemas de instalação."]

. Abra um navegador da Web em um host que tenha uma conexão com a máquina virtual do agente do Console e insira o seguinte URL:
+
https://_ipaddress_[]

. Após efetuar login, configure o agente do Console:
+
.. Especifique a organização a ser associada ao agente do Console.
.. Digite um nome para o sistema.
.. Em *Você está executando em um ambiente seguro?* mantenha o modo restrito desabilitado.
+
Você deve manter o modo restrito desabilitado porque estas etapas descrevem como usar o Console no modo padrão.  Você deve habilitar o modo restrito somente se tiver um ambiente seguro e quiser desconectar esta conta dos serviços de backend.  Se for esse o caso,link:task-quick-start-restricted-mode.html["siga as etapas para começar a usar o NetApp Console no modo restrito"] .

.. Selecione *Vamos começar*.




Se você tiver buckets do Amazon S3 na mesma conta da AWS onde criou o agente do Console, verá um sistema de armazenamento do Amazon S3 aparecer na página *Sistemas* automaticamente. https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Aprenda a gerenciar buckets S3 no NetApp ConsoleP"^]



== Etapa 6: fornecer permissões ao NetApp Console

Agora que você instalou o agente do Console, precisa fornecer ao Console as permissões da AWS que você configurou anteriormente.  Fornecer as permissões permite que o agente do Console gerencie seus dados e infraestrutura de armazenamento na AWS.

[role="tabbed-block"]
====
.Função IAM
--
Anexe a função do IAM que você criou anteriormente à instância do EC2 do agente do Console.

.Passos
. Acesse o console do Amazon EC2.
. Selecione *Instâncias*.
. Selecione a instância do agente do Console.
. Selecione *Ações > Segurança > Modificar função do IAM*.
. Selecione a função do IAM e selecione *Atualizar função do IAM*.


Vá para o https://console.netapp.com["NetApp Console"^] para começar a usar o agente do Console.

--
.Chave de acesso AWS
--
Forneça ao Console a chave de acesso da AWS para um usuário do IAM que tenha as permissões necessárias.

.Passos
. Certifique-se de que o agente correto do Console esteja selecionado no Console.
. Selecione *Administração > Credenciais*.
. Selecione *Credenciais da organização*.
. Selecione *Adicionar credenciais* e siga as etapas do assistente.
+
.. *Localização das credenciais*: Selecione *Amazon Web Services > Agente.
.. *Definir credenciais*: insira uma chave de acesso e uma chave secreta da AWS.
.. *Assinatura do Marketplace*: Associe uma assinatura do Marketplace a essas credenciais assinando agora ou selecionando uma assinatura existente.
.. *Revisar*: Confirme os detalhes sobre as novas credenciais e selecione *Adicionar*.




Vá para o https://console.netapp.com["NetApp Console"^] para começar a usar o agente do Console.

--
====