---
sidebar: sidebar 
permalink: task-upgrade-agent.html 
keywords: upgrade, manual upgrade, agent upgrade, manual agent upgrade, upgrade agent manually, private mode upgrade, offline upgrade, upgrade private mode, connector upgrade, agent upgrade 
summary: 'O agente do Console é atualizado automaticamente quando possui conectividade de saída. Se o seu agente do Console não tiver conectividade de saída, você pode atualizá-lo manualmente (como com o modo privado).' 
---
= Gerenciar atualizações do agente do console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O agente do Console é atualizado automaticamente quando possui conectividade de saída. Se o seu agente do Console não tiver conectividade de saída, você pode atualizá-lo manualmente (como com o modo privado).



== Atualizar o agente do Console

O agente do Console precisa ser reiniciado durante o processo de atualização, portanto, o NetApp Console ficará indisponível durante a atualização.

.Passos
. Baixe o software do agente do Console em https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de suporte da NetApp"^] .
. Copie o instalador para o host Linux.
. Atribua permissões para executar o script.
+
[source, cli]
----
chmod +x /path/NetApp-Console-Agent-Offline-<version>
----
+
Onde <versão> é a versão do agente do Console que você baixou.

. Execute o script de instalação:
+
[source, cli]
----
sudo /path/NetApp-Console-Agent-Offline-<version>
----
+
Onde <versão> é a versão do agente que você baixou.

. Após a conclusão da atualização, você pode verificar a versão do agente acessando *Administração > Suporte > Agentes*.

