= 
:allow-uri-read: 


Depois de instalar e configurar o agente do Console, adicione suas credenciais de nuvem para que o agente do Console tenha as permissões necessárias para executar ações na AWS ou no Azure.

[role="tabbed-block"]
====
.AWS
--
.Antes de começar
Se você acabou de criar essas credenciais da AWS, elas podem levar alguns minutos para ficarem disponíveis.  Aguarde alguns minutos antes de adicionar as credenciais ao Console.

.Passos
. Selecione *Administração > Credenciais*.
. Selecione *Credenciais da organização*.
. Selecione *Adicionar credenciais* e siga as etapas do assistente.
+
.. *Localização das credenciais*: Selecione *Amazon Web Services > Agente.
.. *Definir credenciais*: insira uma chave de acesso e uma chave secreta da AWS.
.. *Assinatura do Marketplace*: Associe uma assinatura do Marketplace a essas credenciais assinando agora ou selecionando uma assinatura existente.
.. *Revisar*: Confirme os detalhes sobre as novas credenciais e selecione *Adicionar*.




Agora você pode ir para o https://console.netapp.com["Console NetApp"^] para começar a usar o agente do Console.

--
.Azul
--
.Antes de começar
Se você acabou de criar essas credenciais do Azure, elas podem levar alguns minutos para ficarem disponíveis.  Aguarde alguns minutos antes de adicionar as credenciais do agente do Console.

.Passos
. Selecione *Administração > Credenciais*.
. Selecione *Adicionar credenciais* e siga as etapas do assistente.
+
.. *Localização das credenciais*: Selecione *Microsoft Azure > Agente*.
.. *Definir credenciais*: insira informações sobre a entidade de serviço do Microsoft Entra que concede as permissões necessárias:
+
*** ID do aplicativo (cliente)
*** ID do diretório (inquilino)
*** Segredo do cliente


.. *Assinatura do Marketplace*: Associe uma assinatura do Marketplace a essas credenciais assinando agora ou selecionando uma assinatura existente.
.. *Revisar*: Confirme os detalhes sobre as novas credenciais e selecione *Adicionar*.




.Resultado
O agente do Console agora tem as permissões necessárias para executar ações no Azure em seu nome.  Agora você pode ir para o https://console.netapp.com["Console NetApp"^] para começar a usar o agente do Console.

--
====