= 
:allow-uri-read: 


. Revise suas seleções para verificar se sua configuração está correta.
+
.. A caixa de seleção *Validar configuração do agente* está marcada por padrão para que o Console valide os requisitos de conectividade de rede durante a implantação. Se o Console falhar ao implantar o agente, ele fornecerá um relatório para ajudar na solução de problemas. Se a implantação for bem-sucedida, nenhum relatório será fornecido.


+
[NOTE]
====
** Se você ainda estiver usando o link:reference-networking-saas-console-previous.html["pontos finais anteriores"] usado para atualizações de agentes, a validação falhará com um erro. Para evitar isso, desmarque a caixa de seleção para ignorar a verificação de validação.
** Durante a instalação, NetApp verifica se o host do agente possui pelo menos 80% do espaço de disco disponível, o que inclui 48 GB em  `/opt` e 32 GB em  `/var` (80 GB no total). Após a instalação, exige que pelo menos 20% do disco total permaneça disponível, o que inclui 12 GB em  `/opt` e 8 GB em  `/var` (20 GB no total).


====

