= 
:allow-uri-read: 


Crie uma função e aplique-a a uma conta de serviço que você usará para a instância de VM do agente do Console.

.Passos
. Crie uma função personalizada no Google Cloud:
+
.. Crie um arquivo YAML que inclua as permissões definidas nolink:reference-permissions-gcp.html["Política do agente do console para o Google Cloud"] .
.. No Google Cloud, ative o Cloud Shell.
.. Carregue o arquivo YAML que inclui as permissões necessárias para o agente do Console.
.. Crie uma função personalizada usando o `gcloud iam roles create` comando.
+
O exemplo a seguir cria uma função chamada "conector" no nível do projeto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentação do Google Cloud: Criação e gerenciamento de funções personalizadas"^]



. Crie uma conta de serviço no Google Cloud:
+
.. No serviço IAM e Admin, selecione *Contas de serviço > Criar conta de serviço*.
.. Insira os detalhes da conta de serviço e selecione *Criar e continuar*.
.. Selecione a função que você acabou de criar.
.. Conclua as etapas restantes para criar a função.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentação do Google Cloud: Criação de uma conta de serviço"^]





.Resultado
Agora você tem uma conta de serviço que pode atribuir à instância de VM do agente do Console.
