= Porta a ser usada para o daemon de encaminhamento DNS com Netavark em uma ponte com privilégios de root.
:allow-uri-read: 


.Antes de começar
Você deve ter o seguinte:

* Privilégios de root para instalar o agente do Console.
* Detalhes sobre um servidor proxy, caso um proxy seja necessário para acesso à Internet a partir do agente do Console.
+
Você tem a opção de configurar um servidor proxy após a instalação, mas isso requer a reinicialização do agente do Console.

* Um certificado assinado pela CA, se o servidor proxy usar HTTPS ou se o proxy for um proxy de interceptação.



NOTE: Não é possível definir um certificado para um servidor proxy transparente ao instalar manualmente o agente do Console. Se precisar definir um certificado para um servidor proxy transparente, você deverá usar o Console de Manutenção após a instalação. Saiba mais sobre olink:reference-connector-maint-console.html["Console de manutenção do agente"] .

.Sobre esta tarefa
O instalador disponível no site de suporte da NetApp pode ser uma versão anterior.  Após a instalação, o agente do Console se atualiza automaticamente se uma nova versão estiver disponível.

.Passos
. Se as variáveis de sistema _http_proxy_ ou _https_proxy_ estiverem definidas no host, remova-as:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se você não remover essas variáveis do sistema, a instalação falhará.

. Baixe o software do agente do Console em https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de suporte da NetApp"^] e, em seguida, copie-o para o host Linux.
+
Você deve baixar o instalador do agente "online" destinado ao uso em sua rede ou na nuvem.

. Atribua permissões para executar o script.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Onde <versão> é a versão do agente do Console que você baixou.

. Execute o script de instalação.
+
[source, cli]
----
./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>

+
You'll need to add proxy information if your network requires a proxy for internet access. You can add either a transparent or explicit proxy. The --proxy and --cacert parameters are optional and you won't be prompted to add them. If you have a proxy server, you will need to enter the parameters as shown.
+
Here is an example configuring an explicit proxy server with a CA-signed certificate:
+
[source,cli]
----


[listing]
----
+
--proxy configures the Console agent to use an HTTP or HTTPS proxy server using one of the following formats:
+
* \http://address:port
* \http://user-name:password@address:port
* \http://domain-name%92user-name:password@address:port
* \https://address:port
* \https://user-name:password@address:port
* \https://domain-name%92user-name:password@address:port
+
Note the following:
+
** The user can be a local user or domain user.
** For a domain user, you must use the ASCII code for a \ as shown above.
** The Console agent doesn't support user names or passwords that include the @ character.
** If the password includes any of the following special characters, you must escape that special character by prepending it with a backslash: & or !
+
For example:
+
\http://bxpproxyuser:netapp1\!@address:3128

+
--cacert specifies a CA-signed certificate to use for HTTPS access between Console agent and the proxy server. This parameter is required for HTTPS proxy servers, intercepting proxy servers, and transparent proxy servers.

+
Here is an example configuring a transparent proxy server. When you configure a transparent proxy, you don't need to define the proxy server. You only add a CA-signed certificate to your Console agent host:

+
[source,cli]
----
 ./NetApp-Console-Agent-v4.0.0 --cacert /tmp/cacert/certificate.cer
[listing]
----
. If you used Podman, you'll need to adjust the aardvark-dns port.
.. SSH to the Console agent virtual machine.
.. Open podman _/usr/share/containers/containers.conf_ file and modify the chosen port for Aardvark DNS service. For example, change it to 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf

[listing]
----
+
For example:
+
[source,text]
----


= Porta a ser usada para o daemon de encaminhamento DNS com Netavark em uma ponte com privilégios de root.



= Modo e DNS ativados.



= Utilizar uma porta alternativa pode ser útil se outros serviços de DNS precisarem de uma porta alternativa.



= executar na máquina.

# dns_bind_port = 54

[listing]
----
.. Reboot the Console agent virtual machine.
//end::main-steps[]

//tag::standard-mode-steps-for-cloud[]
. Wait for the installation to complete.
+
At the end of the installation, the Console agent service (occm) restarts twice if you specified a proxy server.

. Open a web browser from a host that has a connection to the Console agent virtual machine and enter the following URL:
+
https://_ipaddress_

. After you log in, set up the Console agent:
.. Specify the organization to associate with the Console agent.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use the Console in standard mode. You should enable restricted mode only if you have a secure environment and want to disconnect this account from backend services. If that's the case, link:task-quick-start-restricted-mode.html[follow steps to get started with the NetApp Console in restricted mode].
.. Select *Let's start*.

//end::standard-mode-steps-for-cloud[]
----